/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Config.Koneksi_dua;
import Palette.Custom_ButtonRounded;
import Palette.JTable_Custom;
import Palette.JTextfieldRounded;
import Palette.Panelcustom;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahar
 */
public class Form_Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Form_Pelanggan
     */
    private int HalamanSaatIni = 1;
    private int DataperHalaman = 14;
    private int totalpages;

    private final Connection con;// Koneksi database

    public Form_Dashboard() {
        con = Koneksi_dua.con();
        initComponents(); // Inisialisasi komponen GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new JPanel();
        content = new JPanel();
        jLabel5 = new JLabel();
        jLabel1 = new JLabel();
        panelcustom1 = new Panelcustom();
        jLabel3 = new JLabel();
        jLabel2 = new JLabel();
        jLabel4 = new JLabel();
        panelcustom2 = new Panelcustom();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        panelcustom3 = new Panelcustom();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        panelcustom4 = new Panelcustom();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();

        setLayout(new CardLayout());

        main_panel.setLayout(new CardLayout());

        content.setBackground(new Color(255, 255, 255));

        jLabel5.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/Icons/Dashboard Layout.png"))); // NOI18N

        jLabel1.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard");

        panelcustom1.setBackground(new Color(135, 206, 250));
        panelcustom1.setPreferredSize(new Dimension(232, 112));
        panelcustom1.setRoundBottomRight(20);
        panelcustom1.setRoundBottomleft(20);
        panelcustom1.setRoundTopLeft(20);
        panelcustom1.setRoundTopRight(20);

        jLabel3.setBackground(new Color(102, 102, 102));
        jLabel3.setFont(new Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new Color(102, 102, 102));
        jLabel3.setText("Pelanggan");

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/IconsDs/Crowd.png"))); // NOI18N

        jLabel4.setBackground(new Color(102, 102, 102));
        jLabel4.setFont(new Font("SansSerif", 1, 20)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setText("100");

        GroupLayout panelcustom1Layout = new GroupLayout(panelcustom1);
        panelcustom1.setLayout(panelcustom1Layout);
        panelcustom1Layout.setHorizontalGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelcustom1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        panelcustom1Layout.setVerticalGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelcustom1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelcustom2.setBackground(new Color(135, 206, 250));
        panelcustom2.setPreferredSize(new Dimension(232, 112));
        panelcustom2.setRoundBottomRight(20);
        panelcustom2.setRoundBottomleft(20);
        panelcustom2.setRoundTopLeft(20);
        panelcustom2.setRoundTopRight(20);

        jLabel6.setBackground(new Color(102, 102, 102));
        jLabel6.setFont(new Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new Color(102, 102, 102));
        jLabel6.setText("Pelanggan");

        jLabel7.setIcon(new ImageIcon(getClass().getResource("/IconsDs/Crowd.png"))); // NOI18N

        jLabel8.setBackground(new Color(102, 102, 102));
        jLabel8.setFont(new Font("SansSerif", 1, 20)); // NOI18N
        jLabel8.setForeground(new Color(255, 255, 255));
        jLabel8.setText("100");

        GroupLayout panelcustom2Layout = new GroupLayout(panelcustom2);
        panelcustom2.setLayout(panelcustom2Layout);
        panelcustom2Layout.setHorizontalGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelcustom2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(17, 17, 17))
        );
        panelcustom2Layout.setVerticalGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelcustom2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelcustom3.setBackground(new Color(135, 206, 250));
        panelcustom3.setPreferredSize(new Dimension(232, 112));
        panelcustom3.setRoundBottomRight(20);
        panelcustom3.setRoundBottomleft(20);
        panelcustom3.setRoundTopLeft(20);
        panelcustom3.setRoundTopRight(20);

        jLabel9.setBackground(new Color(102, 102, 102));
        jLabel9.setFont(new Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new Color(102, 102, 102));
        jLabel9.setText("Pelanggan");

        jLabel10.setIcon(new ImageIcon(getClass().getResource("/IconsDs/Crowd.png"))); // NOI18N

        jLabel11.setBackground(new Color(102, 102, 102));
        jLabel11.setFont(new Font("SansSerif", 1, 20)); // NOI18N
        jLabel11.setForeground(new Color(255, 255, 255));
        jLabel11.setText("100");

        GroupLayout panelcustom3Layout = new GroupLayout(panelcustom3);
        panelcustom3.setLayout(panelcustom3Layout);
        panelcustom3Layout.setHorizontalGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelcustom3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(17, 17, 17))
        );
        panelcustom3Layout.setVerticalGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(panelcustom3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelcustom4.setBackground(new Color(135, 206, 250));
        panelcustom4.setPreferredSize(new Dimension(232, 112));
        panelcustom4.setRoundBottomRight(20);
        panelcustom4.setRoundBottomleft(20);
        panelcustom4.setRoundTopLeft(20);
        panelcustom4.setRoundTopRight(20);

        jLabel12.setBackground(new Color(102, 102, 102));
        jLabel12.setFont(new Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new Color(102, 102, 102));
        jLabel12.setText("Pelanggan");

        jLabel13.setIcon(new ImageIcon(getClass().getResource("/IconsDs/Crowd.png"))); // NOI18N

        jLabel14.setBackground(new Color(102, 102, 102));
        jLabel14.setFont(new Font("SansSerif", 1, 20)); // NOI18N
        jLabel14.setForeground(new Color(255, 255, 255));
        jLabel14.setText("100");

        GroupLayout panelcustom4Layout = new GroupLayout(panelcustom4);
        panelcustom4.setLayout(panelcustom4Layout);
        panelcustom4Layout.setHorizontalGroup(panelcustom4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelcustom4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelcustom4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(17, 17, 17))
        );
        panelcustom4Layout.setVerticalGroup(panelcustom4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelcustom4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(panelcustom4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel15.setIcon(new ImageIcon(getClass().getResource("/Image/—Pngtree—hand drawn cartoon gourmet catering_3848877 1.png"))); // NOI18N

        GroupLayout contentLayout = new GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelcustom2, GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(panelcustom1, GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelcustom3, GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(panelcustom4, GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 535, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelcustom1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelcustom4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(contentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelcustom2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelcustom3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 466, GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        main_panel.add(content, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel content;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel main_panel;
    private Panelcustom panelcustom1;
    private Panelcustom panelcustom2;
    private Panelcustom panelcustom3;
    private Panelcustom panelcustom4;
    // End of variables declaration//GEN-END:variables

}
