/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Config.Koneksi_dua;
import Palette.Custom_ButtonRounded;
import Palette.JTable_Custom;
import Palette.JTextfieldRounded;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahar
 */
public class Form_Meja extends javax.swing.JPanel {

    /**
     * Creates new form Form_Pelanggan
     */
    private int HalamanSaatIni = 1;
    private int DataperHalaman = 14;
    private int totalpages;

    private final Connection con;// Koneksi database

    public Form_Meja() {
        con = Koneksi_dua.con();
        initComponents(); // Inisialisasi komponen GUI
        loadData(); // Memuat data pelanggan ke dalam JTable
        setTabelModel(); // Mengatur model tabel (misalnya, kolom-kolomnya)
        resetForm(); // Mereset form input menjadi kosong
        pagination(); // Mengatur paginasi untuk tampilan data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJenisKelamin = new ButtonGroup();
        main_panel = new JPanel();
        data_meja = new JPanel();
        jLabel1 = new JLabel();
        btn_tambah = new Custom_ButtonRounded();
        btn_cancel = new Custom_ButtonRounded();
        btn_hapus = new Custom_ButtonRounded();
        jScrollPane1 = new JScrollPane();
        tbl_data = new JTable_Custom();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        btn_first = new Custom_ButtonRounded();
        btn_before = new Custom_ButtonRounded();
        cbx_data = new JComboBox<>();
        btn_next = new Custom_ButtonRounded();
        btn_last = new Custom_ButtonRounded();
        lb_halaman = new JLabel();
        txt_search = new JTextfieldRounded();
        tambah_meja = new JPanel();
        jLabel2 = new JLabel();
        btn_simpan = new Custom_ButtonRounded();
        btn_batal = new Custom_ButtonRounded();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        txt_nama = new JTextfieldRounded();
        jLabel10 = new JLabel();
        txt_id = new JTextfieldRounded();

        setLayout(new CardLayout());

        main_panel.setLayout(new CardLayout());

        data_meja.setBackground(new Color(255, 255, 255));

        jLabel1.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Data Meja");

        btn_tambah.setIcon(new ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_cancel.setIcon(new ImageIcon(getClass().getResource("/Icons/Close5.png"))); // NOI18N
        btn_cancel.setText("Batal");
        btn_cancel.setFillClick(new Color(153, 51, 0));
        btn_cancel.setFillOriginal(new Color(255, 153, 51));
        btn_cancel.setFillOver(new Color(204, 102, 0));
        btn_cancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.setFillClick(new Color(153, 0, 51));
        btn_hapus.setFillOriginal(new Color(255, 0, 51));
        btn_hapus.setFillOver(new Color(204, 0, 51));
        btn_hapus.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_data.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/Icons/Table1.png"))); // NOI18N

        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Icons/Table1.png"))); // NOI18N

        jLabel5.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/Icons/Dashboard Layout.png"))); // NOI18N
        jLabel5.setText(" >");

        btn_first.setText("First Page");
        btn_first.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_before.setText("<");
        btn_before.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_beforeActionPerformed(evt);
            }
        });

        cbx_data.setModel(new DefaultComboBoxModel<>(new String[] { "8", "16", "32", " " }));
        cbx_data.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cbx_dataActionPerformed(evt);
            }
        });

        btn_next.setText(">");
        btn_next.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_last.setText("Last Page");
        btn_last.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        lb_halaman.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        lb_halaman.setForeground(new Color(153, 153, 153));
        lb_halaman.setText("Halaman of Total Halaman");

        txt_search.setText("Search");
        txt_search.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        GroupLayout data_mejaLayout = new GroupLayout(data_meja);
        data_meja.setLayout(data_mejaLayout);
        data_mejaLayout.setHorizontalGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_mejaLayout.createSequentialGroup()
                .addGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(data_mejaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(GroupLayout.Alignment.LEADING, data_mejaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(data_mejaLayout.createSequentialGroup()
                                .addComponent(btn_tambah, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancel, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
            .addGroup(GroupLayout.Alignment.TRAILING, data_mejaLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, data_mejaLayout.createSequentialGroup()
                        .addComponent(lb_halaman)
                        .addGap(384, 384, 384))
                    .addGroup(GroupLayout.Alignment.TRAILING, data_mejaLayout.createSequentialGroup()
                        .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
        );
        data_mejaLayout.setVerticalGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_mejaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 292, GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lb_halaman)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(data_mejaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        main_panel.add(data_meja, "card2");

        tambah_meja.setBackground(new Color(255, 255, 255));

        jLabel2.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Data");

        btn_simpan.setIcon(new ImageIcon(getClass().getResource("/Icons/Paper Plane.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setIcon(new ImageIcon(getClass().getResource("/Icons/Close5.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setFillClick(new Color(153, 51, 0));
        btn_batal.setFillOriginal(new Color(255, 153, 51));
        btn_batal.setFillOver(new Color(204, 102, 0));
        btn_batal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new ImageIcon(getClass().getResource("/Icons/Table1.png"))); // NOI18N

        jLabel7.setIcon(new ImageIcon(getClass().getResource("/Icons/Table1.png"))); // NOI18N

        jLabel8.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/Icons/Dashboard Layout.png"))); // NOI18N
        jLabel8.setText(" >");

        jLabel9.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("ID Meja");

        txt_nama.setText("Nomor Meja");

        jLabel10.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Nomor Meja");

        txt_id.setText("ID Meja");

        GroupLayout tambah_mejaLayout = new GroupLayout(tambah_meja);
        tambah_meja.setLayout(tambah_mejaLayout);
        tambah_mejaLayout.setHorizontalGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tambah_mejaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_mejaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12))
                    .addGroup(tambah_mejaLayout.createSequentialGroup()
                        .addGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txt_id, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txt_nama, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambah_mejaLayout.createSequentialGroup()
                                .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 169, Short.MAX_VALUE))))
        );
        tambah_mejaLayout.setVerticalGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tambah_mejaLayout.createSequentialGroup()
                .addGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_mejaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambah_mejaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel10)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nama, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(tambah_mejaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(330, Short.MAX_VALUE))
        );

        main_panel.add(tambah_meja, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambahActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        main_panel.removeAll();
        main_panel.add(tambah_meja);// Beralih ke panel tambah/edit
        main_panel.repaint();
        main_panel.revalidate();

        try {
            txt_id.setText(setIDKategori()); // Menyiapkan ID pelanggan baru secara otomatis
            if (btn_tambah.getText().equals("UBAH")) { // Jika tombol menunjukkan "UBAH"
                dataTabel(); // Memuat data pelanggan yang dipilih ke form
                btn_simpan.setText("PERBARUI"); // Ubah teks tombol simpan menjadi perbarui
            } else {
                btn_simpan.setText("SIMPAN"); // Jika menambah data, tombol tetap "SIMPAN"
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_firstActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_beforeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_beforeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_beforeActionPerformed

    private void btn_nextActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lastActionPerformed

    private void cbx_dataActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cbx_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_dataActionPerformed

    private void btn_cancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void tbl_dataMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        btn_tambah.setText("UBAH"); // Ubah tombol tambah menjadi "UBAH"
        btn_simpan.setText("PERBARUI"); // Ubah tombol simpan menjadi "PERBARUI"
        btn_cancel.setVisible(true); // Tampilkan tombol batal
        btn_hapus.setVisible(true); // Tampilkan tombol hapus
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void txt_searchKeyTyped(KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        searchData(); // Memanggil fungsi searchData() untuk mencari data berdasarkan kata kunci
    }//GEN-LAST:event_txt_searchKeyTyped

    private void btn_batalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        showPanel();// Kembali ke panel utama
        loadData();// Refresh data di JTable
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_simpanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if (btn_simpan.getText().equals("SIMPAN")) {
            insertData(); // Menyimpan data baru ke database
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            updateData(); // Memperbarui data pelanggan yang sudah ada
        }
    }//GEN-LAST:event_btn_simpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_ButtonRounded btn_batal;
    private Custom_ButtonRounded btn_before;
    private Custom_ButtonRounded btn_cancel;
    private Custom_ButtonRounded btn_first;
    private Custom_ButtonRounded btn_hapus;
    private Custom_ButtonRounded btn_last;
    private Custom_ButtonRounded btn_next;
    private Custom_ButtonRounded btn_simpan;
    private Custom_ButtonRounded btn_tambah;
    private JComboBox<String> cbx_data;
    private JPanel data_meja;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JLabel lb_halaman;
    private JPanel main_panel;
    private ButtonGroup rbJenisKelamin;
    private JPanel tambah_meja;
    private JTable_Custom tbl_data;
    private JTextfieldRounded txt_id;
    private JTextfieldRounded txt_nama;
    private JTextfieldRounded txt_search;
    // End of variables declaration//GEN-END:variables
 // pagination() - Mengatur fungsi pagination untuk Kategori
    private void pagination() {
        // Mengatur tombol halaman pertama
        btn_first.addActionListener(e -> {
            HalamanSaatIni = 1;// Set ke halaman pertama
            loadData(); // Memuat data pada halaman pertama
        });

        // Mengatur tombol halaman sebelumnya
        btn_before.addActionListener(e -> {
            if (HalamanSaatIni > 1) {// Memastikan halaman saat ini lebih dari 1
                HalamanSaatIni--; // Turun ke halaman sebelumnya
                loadData();// Memuat data pada halaman saat ini
            }
        });

        // Mengatur combo box untuk jumlah data per halaman
        cbx_data.addActionListener(e -> {
            DataperHalaman = Integer.parseInt(cbx_data.getSelectedItem().toString());// Mengambil jumlah data per halaman dari combo box
            HalamanSaatIni = 1;// Set ke halaman pertama setiap kali data per halaman diubah
            loadData(); //Memuat data
        });

        // Mengatur tombol halaman berikutnya
        btn_next.addActionListener(e -> {
            if (HalamanSaatIni < totalpages) {// Memastikan belum di halaman terakhir
                HalamanSaatIni++;// Naik ke halaman berikutnya
                loadData();//Memuat data pada halaman baru
            }
        });

        // Mengatur tombol halaman terakhir
        btn_last.addActionListener(e -> {
            HalamanSaatIni = totalpages;// Set ke halaman terakhir
            loadData();// Memuat data pada halaman terakhir
        });
    }

    // calculateTotalPage() - Menghitung total halaman berdasarkan jumlah data dan data per halaman
    private void calculateTotalPage() {
        int totalData = getTotalData();// Mendapatkan total data Kategori
        totalpages = (int) Math.ceil((double) totalData / DataperHalaman);// Menghitung total halaman
    }

    // getTotalData() - Mendapatkan total data Kategori dari database
    private int getTotalData() {
        int totalData = 0;
        try {
            String sql = "SELECT COUNT(*) AS total FROM tbl_kategori";// Query menghitung total data Kategori
            try (PreparedStatement st = con.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery(); // Eksekusi query
                if (rs.next()) {
                    totalData = rs.getInt("total");// Mendapatkan jumlah total dari kolom "total"
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);
        }
        return totalData;// Mengembalikan jumlah data
    }

    // loadData() - Memuat data Kategori ke dalam JTable berdasarkan halaman saat ini
    private void loadData() {
        calculateTotalPage();// Menghitung total halaman
        int totalData = getTotalData();// Mendapatkan total data Kategori
        lb_halaman.setText(String.valueOf("Halaman " + HalamanSaatIni + " Dari total data " + totalData)); // Menampilkan halaman saat ini

        int startIndex = (HalamanSaatIni - 1) * DataperHalaman;// Menentukan indeks awal data berdasarkan halaman saat ini
        getData(startIndex, DataperHalaman, (DefaultTableModel) tbl_data.getModel());// Mendapatkan data untuk ditampilkan di tabel
        btn_hapus.setVisible(false); // Menyembunyikan tombol hapus
        btn_cancel.setVisible(false); // Menyembunyikan tombol batal
    }

    // showPanel() - Mengatur tampilan panel utama
    private void showPanel() {
        main_panel.removeAll();// Menghapus semua komponen di panel utama
        main_panel.add(new Form_Meja());// Menambahkan panel Form_Kategori ke panel utama
        main_panel.repaint();// Menggambar ulang panel utama
        main_panel.revalidate();// Memastikan perubahan diterapkan
    }

    // resetForm() - Mengosongkan input form Kategori
    private void resetForm() {
        txt_id.setText("");
        txt_nama.setText("");
    }

    // setTabelModel() - Mengatur model tabel dengan kolom-kolom yang sesuai
    private void setTabelModel() {
        String[] columnNames = {
            "ID",
            "Nama",
            "Deskripsi"
        };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Membuat model tabel dengan kolom yang ditentukan
        tbl_data.setModel(model); // Mengatur model tabel untuk JTable
        loadData(); // Memuat data ke dalam tabel
    }

    // getData() - Mendapatkan data Kategori dari database dengan batasan jumlah data per halaman
    private void getData(int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0); // Mengosongkan data yang ada di tabel

        try {
            String sql = "SELECT * FROM tbl_kategori LIMIT ?,?"; // Query dengan limit berdasarkan halaman
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setInt(1, startIndex); // Indeks awal
                st.setInt(2, entriesPage); // Jumlah data per halaman
                ResultSet rs = st.executeQuery(); // Eksekusi query

                while (rs.next()) {
                    String IdKategori = rs.getString("ID_Kategori");
                    String NamaKategori = rs.getString("Nama_Kategori");
                    String deskripsiKategori = rs.getString("Deskripsi");

                    Object[] rowData = {IdKategori, NamaKategori, deskripsiKategori}; // Data Kategori
                    model.addRow(rowData); // Menambahkan baris data ke dalam tabel
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);

        }
    }

    // setIDKategori() - Mengatur ID Kategori secara otomatis
    private String setIDKategori() throws SQLException {
        String urutan = null;
        Date now = new Date();
        SimpleDateFormat noFormat = new SimpleDateFormat("yyMM"); // Format tanggal sebagai bagian dari ID
        String no = noFormat.format(now);

        String sql = "SELECT RIGHT(ID_Kategori, 3) AS Nomor FROM tbl_kategori WHERE ID_Kategori LIKE '" + no + "%' ORDER BY ID_Kategori DESC LIMIT 1";

        try (PreparedStatement st = con.prepareStatement(sql)) {
            ResultSet rs = st.executeQuery(); // Eksekusi query

            if (rs.next()) {
                int nomor = Integer.parseInt(rs.getString("nomor")) + 1; // Menambah nomor urut
                urutan = no + String.format("%03d", nomor); // Format ID baru
            } else {
                urutan = no + "001"; // ID awal jika tidak ada data
            }
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);
        }
        return urutan;
    }

    // validasiNama() - diperlukan untuk memastikan bahwa setiap nama kategori yang dimasukkan pengguna unik
    //Menggunakan tipe data boolean untuk fungsi validasiNama bertujuan
    //agar fungsi ini dapat memberikan hasil berupa status validasi dengan dua kemungkinan:true dan false
    public boolean validasiNama() {
        // Variabel untuk menyimpan status validasi, default-nya adalah false
        boolean valid = false;

        // Mengambil data dari form
        String IdKategori = txt_id.getText(); // ID kategori yang diinput pengguna
        String NamaKategori = txt_nama.getText(); // Nama kategori yang diinput pengguna

        // Query SQL untuk memeriksa apakah nama kategori sudah ada di database,
        // kecuali untuk kategori dengan ID yang sedang diupdate (ID_Kategori != IdKategori)
        // Menggunakan LIKE BINARY agar pencarian bersifat case-sensitive
        String sql = "SELECT Nama_Kategori FROM tbl_kategori WHERE ID_Kategori!='" + IdKategori + "' AND Nama_Kategori LIKE BINARY '" + NamaKategori + "'";

        try (PreparedStatement st = con.prepareStatement(sql)) {
            // Eksekusi query
            ResultSet rs = st.executeQuery();

            // Mengecek apakah hasil query mengembalikan data
            if (rs.next()) {
                // Jika ada data, berarti nama kategori sudah ada
                JOptionPane.showMessageDialog(this,
                        "Nama Kategori sudah ada\nSilahkan input nama kategori yang berbeda",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                // Jika tidak ada data, berarti nama kategori valid
                valid = true;
            }
        } catch (SQLException e) {
            // Menangkap dan mencatat error jika terjadi kesalahan SQL
            Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);
        }

        // Mengembalikan status validasi (true jika valid, false jika tidak valid)
        return valid;
    }

    // insertData() - Menambahkan data Kategori ke database
    private void insertData() {
        String IdKategori = txt_id.getText();
        String NamaKategori = txt_nama.getText();

        // Validasi input data
        if (IdKategori.isEmpty() || NamaKategori.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!validasiNama()) {
            return;
        }

        // Insert data ke database
        try {
            String sql = "INSERT INTO tbl_kategori (ID_Kategori, Nama_Kategori, Deskripsi) VALUES (?,?,?)";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, IdKategori);
                st.setString(2, NamaKategori);

                int rowInserted = st.executeUpdate();// Menjalankan perintah insert
                if (rowInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                    resetForm(); // Kosongkan text field setelah data berhasil ditambahkan
                    loadData();  // Memuat data ke tampilan JTable atau komponen lainnya
                    showPanel();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // dataTabel() - Menampilkan data Kategori dari JTable ke dalam form untuk diperbarui
    private void dataTabel() {
        int row = tbl_data.getSelectedRow(); // Mendapatkan baris yang dipilih pada tabel
        if (row == -1) { // Jika tidak ada baris yang dipilih
            JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Keluar dari metode
        }

        data_meja.setVisible(false); // Menyembunyikan panel view
        tambah_meja.setVisible(true); // Menampilkan panel tambah/edit

        jLabel7.setText("PERBARUI DATA Kategori"); // Mengubah teks label menjadi "PERBARUI DATA Kategori"
        txt_id.setEnabled(false); // Menonaktifkan field ID Kategori agar tidak bisa diedit

        // Mengisi field form dengan data dari baris yang dipilih
        txt_id.setText(tbl_data.getValueAt(row, 0).toString());
        txt_nama.setText(tbl_data.getValueAt(row, 1).toString());
    }

    // updateData() - Memperbarui data Kategori di database
    private void updateData() {
        // Mengambil data dari form
        String IdKategori = txt_id.getText();
        String NamaKategori = txt_nama.getText();

        // Validasi input data
        if (IdKategori.isEmpty() || NamaKategori.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Insert data ke database
        try {
            String sql = "UPDATE tbl_kategori SET Nama_Kategori=?, Deskripsi=? WHERE ID_Kategori=?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, NamaKategori);
                st.setString(3, IdKategori);

                int rowUpdated = st.executeUpdate();
                if (rowUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
                    resetForm();// Kosongkan form
                    loadData();  // Refresh data di JTable
                    showPanel(); // Tampilkan panel utama
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // hapusData() - Menghapus data Kategori dari database
    private void hapusData() {
        int row = tbl_data.getSelectedRow(); // Mendapatkan baris yang dipilih
        if (row == -1) { // Jika tidak ada baris yang dipilih
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Keluar dari metode
        }

        String IdKategori = tbl_data.getValueAt(row, 0).toString(); // Mendapatkan ID Kategori dari baris yang dipilih

        // Konfirmasi penghapusan
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM tbl_kategori WHERE ID_Kategori=?";
                try (PreparedStatement st = con.prepareStatement(sql)) {
                    st.setString(1, IdKategori);

                    int rowDeleted = st.executeUpdate(); // Eksekusi penghapusan
                    if (rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                        loadData(); // Refresh data di JTable
                    }
                }
            } catch (SQLException e) {
                Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }

    // searchData() - Mencari data Kategori berdasarkan nama atau alamat
    private void searchData() {
        String kataKunci = txt_search.getText(); // Mengambil kata kunci dari text field pencarian

        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);// Mengosongkan data di tabel sebelum memuat hasil pencarian

        try {
            String sql = "SELECT * FROM tbl_kategori WHERE Nama_Kategori LIKE ? OR Deskripsi LIKE ?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, "%" + kataKunci + "%"); // Parameter pencarian pada kolom Nama
                st.setString(2, "%" + kataKunci + "%");// Parameter pencarian pada kolom Alamat

                ResultSet rs = st.executeQuery();

                while (rs.next()) {
                    String IdKategori = rs.getString("ID_Kategori");
                    String NamaKategori = rs.getString("Nama_Kategori");
                    String deskripsiKategori = rs.getString("Deskripsi");

                    Object[] rowData = {IdKategori, NamaKategori, deskripsiKategori};
                    model.addRow(rowData);// Tambahkan hasil pencarian ke dalam JTable
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_Meja.class.getName()).log(Level.SEVERE, null, e);

        }
    }
}
