/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Config.Koneksi_dua;
import Palette.Custom_ButtonRounded;
import Palette.Custom_JPasswordFieldRounded;
import Palette.JTable_Custom;
import Palette.JTextfieldRounded;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;
import View.FormLogin;

/**
 *
 * @author mahar
 */
public class Form_User extends javax.swing.JPanel {

    /**
     * Creates new form Form_Pelanggan
     */
    private int HalamanSaatIni = 1;
    private int DataperHalaman = 14;
    private int totalpages;

    private final Connection con;// Koneksi database
    private FormLogin formlogin;

    public Form_User() {
        con = Koneksi_dua.con();
        formlogin = new FormLogin();
        initComponents(); // Inisialisasi komponen GUI
        loadData(); // Memuat data pelanggan ke dalam JTable
        setTabelModel(); // Mengatur model tabel (misalnya, kolom-kolomnya)
        resetForm(); // Mereset form input menjadi kosong
        paginationPelanggan(); // Mengatur paginasi untuk tampilan data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJenisKelamin = new ButtonGroup();
        main_panel = new JPanel();
        data_user = new JPanel();
        jLabel1 = new JLabel();
        btn_tambah = new Custom_ButtonRounded();
        btn_cancel = new Custom_ButtonRounded();
        btn_hapus = new Custom_ButtonRounded();
        jScrollPane1 = new JScrollPane();
        tbl_data = new JTable_Custom();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        btn_first = new Custom_ButtonRounded();
        btn_before = new Custom_ButtonRounded();
        cbx_data = new JComboBox<>();
        btn_next = new Custom_ButtonRounded();
        btn_last = new Custom_ButtonRounded();
        lb_halaman = new JLabel();
        txt_search = new JTextfieldRounded();
        tambah_user = new JPanel();
        jLabel2 = new JLabel();
        btn_simpan = new Custom_ButtonRounded();
        btn_batal = new Custom_ButtonRounded();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        txt_email = new JTextfieldRounded();
        jLabel10 = new JLabel();
        txt_id = new JTextfieldRounded();
        txt_nama = new JTextfieldRounded();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        txt_username = new JTextfieldRounded();
        lb_password = new JLabel();
        txt_password = new Custom_JPasswordFieldRounded();
        jLabel12 = new JLabel();
        cbx_level = new JComboBox<>();
        jLabel11 = new JLabel();
        txt_rfid = new JTextfieldRounded();

        setLayout(new CardLayout());

        main_panel.setLayout(new CardLayout());

        data_user.setBackground(new Color(255, 255, 255));

        jLabel1.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Data User");

        btn_tambah.setIcon(new ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_cancel.setIcon(new ImageIcon(getClass().getResource("/Icons/Close5.png"))); // NOI18N
        btn_cancel.setText("Batal");
        btn_cancel.setFillClick(new Color(153, 51, 0));
        btn_cancel.setFillOriginal(new Color(255, 153, 51));
        btn_cancel.setFillOver(new Color(204, 102, 0));
        btn_cancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.setFillClick(new Color(153, 0, 51));
        btn_hapus.setFillOriginal(new Color(255, 0, 51));
        btn_hapus.setFillOver(new Color(204, 0, 51));
        btn_hapus.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_data.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/Icons/Icon6.png"))); // NOI18N

        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Icons/Icon6.png"))); // NOI18N

        jLabel5.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/Icons/Sorting.png"))); // NOI18N
        jLabel5.setText(" >");

        btn_first.setText("First Page");
        btn_first.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_before.setText("<");
        btn_before.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_beforeActionPerformed(evt);
            }
        });

        cbx_data.setModel(new DefaultComboBoxModel<>(new String[] { "8", "16", "32", " " }));
        cbx_data.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cbx_dataActionPerformed(evt);
            }
        });

        btn_next.setText(">");
        btn_next.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_last.setText("Last Page");
        btn_last.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        lb_halaman.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        lb_halaman.setForeground(new Color(153, 153, 153));
        lb_halaman.setText("Halaman of Total Halaman");

        txt_search.setText("Search");
        txt_search.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        GroupLayout data_userLayout = new GroupLayout(data_user);
        data_user.setLayout(data_userLayout);
        data_userLayout.setHorizontalGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_userLayout.createSequentialGroup()
                .addGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(data_userLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(GroupLayout.Alignment.LEADING, data_userLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(data_userLayout.createSequentialGroup()
                                .addComponent(btn_tambah, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancel, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
            .addGroup(GroupLayout.Alignment.TRAILING, data_userLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, data_userLayout.createSequentialGroup()
                        .addComponent(lb_halaman)
                        .addGap(384, 384, 384))
                    .addGroup(GroupLayout.Alignment.TRAILING, data_userLayout.createSequentialGroup()
                        .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
        );
        data_userLayout.setVerticalGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_userLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 292, GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lb_halaman)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(data_userLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        main_panel.add(data_user, "card2");

        tambah_user.setBackground(new Color(255, 255, 255));

        jLabel2.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Data");

        btn_simpan.setIcon(new ImageIcon(getClass().getResource("/Icons/Paper Plane.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setIcon(new ImageIcon(getClass().getResource("/Icons/Close5.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setFillClick(new Color(153, 51, 0));
        btn_batal.setFillOriginal(new Color(255, 153, 51));
        btn_batal.setFillOver(new Color(204, 102, 0));
        btn_batal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new ImageIcon(getClass().getResource("/Icons/Icon6.png"))); // NOI18N

        jLabel7.setIcon(new ImageIcon(getClass().getResource("/Icons/Icon6.png"))); // NOI18N

        jLabel8.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/Icons/Sorting.png"))); // NOI18N
        jLabel8.setText(" >");

        jLabel9.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("ID User");

        txt_email.setText("Email");

        jLabel10.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Email");

        txt_id.setText("ID User");

        txt_nama.setText("Nama User");

        jLabel13.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Nama User");

        jLabel14.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("Username");

        txt_username.setText("Username");

        lb_password.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        lb_password.setText("Password");

        txt_password.setText("password");
        txt_password.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jLabel12.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Level");

        cbx_level.setModel(new DefaultComboBoxModel<>(new String[] { "Pilih Level", "Admin", "User" }));

        jLabel11.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("RF ID");

        txt_rfid.setText("RF ID");

        GroupLayout tambah_userLayout = new GroupLayout(tambah_user);
        tambah_user.setLayout(tambah_userLayout);
        tambah_userLayout.setHorizontalGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tambah_userLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_userLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12))
                    .addGroup(tambah_userLayout.createSequentialGroup()
                        .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(txt_id, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txt_username, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambah_userLayout.createSequentialGroup()
                                .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(tambah_userLayout.createSequentialGroup()
                                .addComponent(cbx_level, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(169, Short.MAX_VALUE))
                            .addGroup(tambah_userLayout.createSequentialGroup()
                                .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_email, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_password)
                                    .addComponent(txt_password, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_rfid, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        tambah_userLayout.setVerticalGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tambah_userLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rfid, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_userLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nama, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_username, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(tambah_userLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_batal, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tambah_userLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lb_password)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_password, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx_level, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        main_panel.add(tambah_user, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambahActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        main_panel.removeAll();
        main_panel.add(tambah_user);// Beralih ke panel tambah/edit
        main_panel.repaint();
        main_panel.revalidate();

        try {
            txt_id.setText(SetIDUser()); // Menyiapkan ID pelanggan baru secara otomatis
            if (btn_tambah.getText().equals("UBAH")) { // Jika tombol menunjukkan "UBAH"
                dataTabel(); // Memuat data pelanggan yang dipilih ke form
                btn_simpan.setText("PERBARUI"); // Ubah teks tombol simpan menjadi perbarui
            } else {
                btn_simpan.setText("SIMPAN"); // Jika menambah data, tombol tetap "SIMPAN"
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_User.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_firstActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_beforeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_beforeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_beforeActionPerformed

    private void btn_nextActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lastActionPerformed

    private void cbx_dataActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cbx_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_dataActionPerformed

    private void btn_cancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void tbl_dataMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        btn_tambah.setText("UBAH"); // Ubah tombol tambah menjadi "UBAH"
        btn_simpan.setText("PERBARUI"); // Ubah tombol simpan menjadi "PERBARUI"
        btn_cancel.setVisible(true); // Tampilkan tombol batal
        btn_hapus.setVisible(true); // Tampilkan tombol hapus
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void txt_searchKeyTyped(KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        searchData(); // Memanggil fungsi searchData() untuk mencari data berdasarkan kata kunci
    }//GEN-LAST:event_txt_searchKeyTyped

    private void btn_batalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        showPanel();// Kembali ke panel utama
        loadData();// Refresh data di JTable
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_simpanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if (btn_simpan.getText().equals("SIMPAN")) {
            insertData(); // Menyimpan data baru ke database
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            updateData(); // Memperbarui data pelanggan yang sudah ada
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_passwordActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_ButtonRounded btn_batal;
    private Custom_ButtonRounded btn_before;
    private Custom_ButtonRounded btn_cancel;
    private Custom_ButtonRounded btn_first;
    private Custom_ButtonRounded btn_hapus;
    private Custom_ButtonRounded btn_last;
    private Custom_ButtonRounded btn_next;
    private Custom_ButtonRounded btn_simpan;
    private Custom_ButtonRounded btn_tambah;
    private JComboBox<String> cbx_data;
    private JComboBox<String> cbx_level;
    private JPanel data_user;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JLabel lb_halaman;
    private JLabel lb_password;
    private JPanel main_panel;
    private ButtonGroup rbJenisKelamin;
    private JPanel tambah_user;
    private JTable_Custom tbl_data;
    private JTextfieldRounded txt_email;
    private JTextfieldRounded txt_id;
    private JTextfieldRounded txt_nama;
    private Custom_JPasswordFieldRounded txt_password;
    private JTextfieldRounded txt_rfid;
    private JTextfieldRounded txt_search;
    private JTextfieldRounded txt_username;
    // End of variables declaration//GEN-END:variables
// paginationPelanggan() - Mengatur fungsi pagination
    private void paginationPelanggan() {
        btn_first.addActionListener(e -> {
            HalamanSaatIni = 1;
            loadData();
        });

        btn_before.addActionListener(e -> {
            if (HalamanSaatIni > 1) {
                HalamanSaatIni--;
                loadData();
            }
        });

        cbx_data.addActionListener(e -> {
            DataperHalaman = Integer.parseInt(cbx_data.getSelectedItem().toString());
            HalamanSaatIni = 1;
            loadData();
        });

        btn_next.addActionListener(e -> {
            if (HalamanSaatIni < totalpages) {
                HalamanSaatIni++;
                loadData();
            }
        });

        btn_last.addActionListener(e -> {
            HalamanSaatIni = totalpages;
            loadData();
        });
    }

    private void calculateTotalPage() {
        int totalData = getTotalData();
        totalpages = (int) Math.ceil((double) totalData / DataperHalaman);
    }

    private int getTotalData() {
        int totalData = 0;
        try {
            String sql = "SELECT COUNT(*) AS total FROM tbl_user";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    totalData = rs.getInt("total");
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_User.class.getName()).log(Level.SEVERE, null, e);
        }
        return totalData;
    }

    private void loadData() {
        calculateTotalPage();
        int totalData = getTotalData();
        lb_halaman.setText("Halaman " + HalamanSaatIni + " Dari total data " + totalData);

        int startIndex = (HalamanSaatIni - 1) * DataperHalaman;
        getData(startIndex, DataperHalaman, (DefaultTableModel) tbl_data.getModel());
        btn_hapus.setVisible(false);
        btn_cancel.setVisible(false);
    }

    private void showPanel() {
        main_panel.removeAll();
        main_panel.add(new Form_User());
        main_panel.repaint();
        main_panel.revalidate();
    }

    private void resetForm() {
        txt_id.setText("");
        txt_rfid.setText("");
        txt_nama.setText("");
        txt_username.setText("");
        txt_email.setText("");
        txt_password.setText("");
        cbx_level.setSelectedItem("Pilih Level");
    }

    private void setTabelModel() {
        String[] columnNames = {"ID", "RFID", "Nama User", "Username", "Email", "Level"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        tbl_data.setModel(model);
        loadData();
    }

    private void getData(int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0);
        try {
            String sql = "SELECT * FROM tbl_user LIMIT ?,?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setInt(1, startIndex);
                st.setInt(2, entriesPage);
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    Object[] rowData = {
                        rs.getString("ID_User"),
                        rs.getString("RFID"),
                        rs.getString("Nama_User"),
                        rs.getString("Username"),
                        rs.getString("Email"),
                        rs.getString("Level")
                    };
                    model.addRow(rowData);
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_User.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private String SetIDUser() throws SQLException {
        String urutan;
        Date now = new Date();
        SimpleDateFormat noFormat = new SimpleDateFormat("yyMM");
        String no = noFormat.format(now);
        String sql = "SELECT RIGHT(ID_User, 3) AS nomor FROM tbl_user WHERE ID_User LIKE ? ORDER BY ID_User DESC LIMIT 1";
        try (PreparedStatement st = con.prepareStatement(sql)) {
            st.setString(1, no + "%");
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                int nomor = Integer.parseInt(rs.getString("nomor")) + 1;
                urutan = no + String.format("%03d", nomor);
            } else {
                urutan = no + "001";
            }
        }
        return urutan;
    }

    private void insertData() {
        String IdUser = txt_id.getText();
        String RfidUser = txt_rfid.getText();
        String NamaUser = txt_nama.getText();
        String UserName = txt_username.getText();
        String Email = txt_email.getText();
        String Password = formlogin.getMd5java(txt_password.getText());
        String LevelUser = cbx_level.getSelectedItem().toString();

        if (IdUser.isEmpty() || RfidUser.isEmpty() || NamaUser.isEmpty() || UserName.isEmpty() || Email.isEmpty()
                || Password.isEmpty() || LevelUser.equals("Pilih Level")) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi dan Dipilih!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO tbl_user (ID_User, RFID, Nama_User, Username, Email, Password, Level) VALUES (?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, IdUser);
                st.setString(2, RfidUser);
                st.setString(3, NamaUser);
                st.setString(4, UserName);
                st.setString(5, Email);
                st.setString(6, Password);
                st.setString(7, LevelUser);

                if (st.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_User.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void dataTabel() {
        data_user.setVisible(false);
        tambah_user.setVisible(true);
        int row = tbl_data.getSelectedRow();
        jLabel2.setText("Perbarui Data");
        txt_id.setEnabled(false);
        lb_password.setVisible(false);
        txt_password.setVisible(false);

        txt_id.setText(tbl_data.getValueAt(row, 0).toString());
        txt_rfid.setText(tbl_data.getValueAt(row, 1).toString());
        txt_nama.setText(tbl_data.getValueAt(row, 2).toString());
        txt_username.setText(tbl_data.getValueAt(row, 3).toString());
        txt_email.setText(tbl_data.getValueAt(row, 4).toString());
        cbx_level.setSelectedItem(tbl_data.getValueAt(row, 5).toString());
    }

    private void updateData() {
        String IdUser = txt_id.getText();
        String RfidUser = txt_rfid.getText();
        String NamaUser = txt_nama.getText();
        String UserName = txt_username.getText();
        String Email = txt_email.getText();
        String LevelUser = cbx_level.getSelectedItem().toString();

        if (IdUser.isEmpty() || RfidUser.isEmpty() || NamaUser.isEmpty() || UserName.isEmpty() || Email.isEmpty()
                || LevelUser.equals("Pilih Level")) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi dan Dipilih!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "UPDATE tbl_user SET RFID=?, Nama_User=?, Username=?, Email=?, Level=? WHERE ID_User=?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, RfidUser);
                st.setString(2, NamaUser);
                st.setString(3, UserName);
                st.setString(4, Email);
                st.setString(5, LevelUser);
                st.setString(6, IdUser);

                if (st.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_User.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void hapusData() {
        int row = tbl_data.getSelectedRow();
        String IdUser = tbl_data.getValueAt(row, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM tbl_user WHERE ID_User=?";
                try (PreparedStatement st = con.prepareStatement(sql)) {
                    st.setString(1, IdUser);

                    if (st.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                        loadData();
                    }
                }
            } catch (SQLException e) {
                Logger.getLogger(Form_User.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }

    private void searchData() {
        String kataKunci = txt_search.getText();
        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);

        try {
            String sql = "SELECT * FROM tbl_user WHERE Nama_User LIKE ? OR Email LIKE ?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");

                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    Object[] rowData = {
                        rs.getString("ID_User"),
                        rs.getString("RFID"),
                        rs.getString("Nama_User"),
                        rs.getString("Username"),
                        rs.getString("Email"),
                        rs.getString("Level")
                    };
                    model.addRow(rowData);
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_User.class.getName()).log(Level.SEVERE, null, e);
        }
    }

}
