/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Config.Koneksi_dua;
import Palette.Custom_ButtonRounded;
import Palette.JTable_Custom;
import Palette.JTextfieldRounded;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahar
 */
public class Form_Pelanggan extends javax.swing.JPanel {

    /**
     * Creates new form Form_Pelanggan
     */
    private int HalamanSaatIni = 1;
    private int DataperHalaman = 14;
    private int totalpages;

    private final Connection con;// Koneksi database

    public Form_Pelanggan() {
        con = Koneksi_dua.con();
        initComponents(); // Inisialisasi komponen GUI
        loadData(); // Memuat data pelanggan ke dalam JTable
        setTabelModel(); // Mengatur model tabel (misalnya, kolom-kolomnya)
        resetForm(); // Mereset form input menjadi kosong
        paginationPelanggan(); // Mengatur paginasi untuk tampilan data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJenisKelamin = new ButtonGroup();
        main_panel = new JPanel();
        data_pelanggan = new JPanel();
        jLabel1 = new JLabel();
        btn_tambah = new Custom_ButtonRounded();
        btn_cancel = new Custom_ButtonRounded();
        btn_hapus = new Custom_ButtonRounded();
        jScrollPane1 = new JScrollPane();
        tbl_data = new JTable_Custom();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        btn_first = new Custom_ButtonRounded();
        btn_before = new Custom_ButtonRounded();
        cbx_data = new JComboBox<>();
        btn_next = new Custom_ButtonRounded();
        btn_last = new Custom_ButtonRounded();
        lb_halaman = new JLabel();
        txt_search = new JTextfieldRounded();
        tambah_pelanggan = new JPanel();
        jLabel2 = new JLabel();
        btn_simpan = new Custom_ButtonRounded();
        btn_batal = new Custom_ButtonRounded();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        txt_nama = new JTextfieldRounded();
        jLabel10 = new JLabel();
        txt_id = new JTextfieldRounded();
        jLabel11 = new JLabel();
        txt_alamat = new JTextfieldRounded();
        jLabel12 = new JLabel();
        txt_nohp = new JTextfieldRounded();
        jLabel13 = new JLabel();
        rb_laki = new JRadioButton();
        rb_perempuan = new JRadioButton();

        setLayout(new CardLayout());

        main_panel.setLayout(new CardLayout());

        data_pelanggan.setBackground(new Color(255, 255, 255));

        jLabel1.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Data Pelanggan");

        btn_tambah.setIcon(new ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_cancel.setIcon(new ImageIcon(getClass().getResource("/Icons/Close5.png"))); // NOI18N
        btn_cancel.setText("Batal");
        btn_cancel.setFillClick(new Color(153, 51, 0));
        btn_cancel.setFillOriginal(new Color(255, 153, 51));
        btn_cancel.setFillOver(new Color(204, 102, 0));
        btn_cancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.setFillClick(new Color(153, 0, 51));
        btn_hapus.setFillOriginal(new Color(255, 0, 51));
        btn_hapus.setFillOver(new Color(204, 0, 51));
        btn_hapus.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_data.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/Icons/pelanggan.png"))); // NOI18N

        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Icons/pelanggan.png"))); // NOI18N

        jLabel5.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/Icons/Dashboard Layout.png"))); // NOI18N
        jLabel5.setText(" >");

        btn_first.setText("First Page");
        btn_first.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_before.setText("<");
        btn_before.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_beforeActionPerformed(evt);
            }
        });

        cbx_data.setModel(new DefaultComboBoxModel<>(new String[] { "8", "16", "32", " " }));
        cbx_data.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cbx_dataActionPerformed(evt);
            }
        });

        btn_next.setText(">");
        btn_next.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_last.setText("Last Page");
        btn_last.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        lb_halaman.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        lb_halaman.setForeground(new Color(153, 153, 153));
        lb_halaman.setText("Halaman of Total Halaman");

        txt_search.setText("Search");
        txt_search.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        GroupLayout data_pelangganLayout = new GroupLayout(data_pelanggan);
        data_pelanggan.setLayout(data_pelangganLayout);
        data_pelangganLayout.setHorizontalGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(data_pelangganLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(GroupLayout.Alignment.LEADING, data_pelangganLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(data_pelangganLayout.createSequentialGroup()
                                .addComponent(btn_tambah, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancel, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                        .addComponent(lb_halaman)
                        .addGap(384, 384, 384))
                    .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                        .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
        );
        data_pelangganLayout.setVerticalGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 292, GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lb_halaman)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        main_panel.add(data_pelanggan, "card2");

        tambah_pelanggan.setBackground(new Color(255, 255, 255));

        jLabel2.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Data");

        btn_simpan.setIcon(new ImageIcon(getClass().getResource("/Icons/Paper Plane.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setIcon(new ImageIcon(getClass().getResource("/Icons/Close5.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setFillClick(new Color(153, 51, 0));
        btn_batal.setFillOriginal(new Color(255, 153, 51));
        btn_batal.setFillOver(new Color(204, 102, 0));
        btn_batal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new ImageIcon(getClass().getResource("/Icons/pelanggan.png"))); // NOI18N

        jLabel7.setIcon(new ImageIcon(getClass().getResource("/Icons/pelanggan.png"))); // NOI18N

        jLabel8.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/Icons/Dashboard Layout.png"))); // NOI18N
        jLabel8.setText(" >");

        jLabel9.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("ID Pelanggan");

        txt_nama.setText("Nama Pelanggan");

        jLabel10.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Nama Pelanggan");

        txt_id.setText("ID Pelanggan");

        jLabel11.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Jenis Kelamin");

        txt_alamat.setText("Alamat");

        jLabel12.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("No. Hp");

        txt_nohp.setText("No Hp");

        jLabel13.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Alamat");

        rb_laki.setText("Laki - Laki");

        rb_perempuan.setText("Perempuan");

        GroupLayout tambah_pelangganLayout = new GroupLayout(tambah_pelanggan);
        tambah_pelanggan.setLayout(tambah_pelangganLayout);
        tambah_pelangganLayout.setHorizontalGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tambah_pelangganLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_pelangganLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12))
                    .addGroup(tambah_pelangganLayout.createSequentialGroup()
                        .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(txt_id, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txt_alamat, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambah_pelangganLayout.createSequentialGroup()
                                .addComponent(rb_laki)
                                .addGap(18, 18, 18)
                                .addComponent(rb_perempuan)))
                        .addGap(88, 88, 88)
                        .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txt_nama, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_nohp, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambah_pelangganLayout.createSequentialGroup()
                                .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 169, Short.MAX_VALUE))))
        );
        tambah_pelangganLayout.setVerticalGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tambah_pelangganLayout.createSequentialGroup()
                .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_pelangganLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(tambah_pelangganLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel10)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nama, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_pelangganLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_laki)
                            .addComponent(rb_perempuan))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambah_pelangganLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_alamat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_batal, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tambah_pelangganLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txt_nohp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        main_panel.add(tambah_pelanggan, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambahActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        main_panel.removeAll();
        main_panel.add(tambah_pelanggan);// Beralih ke panel tambah/edit
        main_panel.repaint();
        main_panel.revalidate();

        try {
            txt_id.setText(setIDPelanggan()); // Menyiapkan ID pelanggan baru secara otomatis
            if (btn_tambah.getText().equals("UBAH")) { // Jika tombol menunjukkan "UBAH"
                dataTabel(); // Memuat data pelanggan yang dipilih ke form
                btn_simpan.setText("PERBARUI"); // Ubah teks tombol simpan menjadi perbarui
            } else {
                btn_simpan.setText("SIMPAN"); // Jika menambah data, tombol tetap "SIMPAN"
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        showPanel();// Kembali ke panel utama
        loadData();// Refresh data di JTable
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_firstActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_beforeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_beforeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_beforeActionPerformed

    private void btn_nextActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lastActionPerformed

    private void cbx_dataActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cbx_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_dataActionPerformed

    private void btn_cancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_simpanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if (btn_simpan.getText().equals("SIMPAN")) {
            insertData(); // Menyimpan data baru ke database
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            updateData(); // Memperbarui data pelanggan yang sudah ada
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tbl_dataMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        btn_tambah.setText("UBAH"); // Ubah tombol tambah menjadi "UBAH"
        btn_simpan.setText("PERBARUI"); // Ubah tombol simpan menjadi "PERBARUI"
        btn_cancel.setVisible(true); // Tampilkan tombol batal
        btn_hapus.setVisible(true); // Tampilkan tombol hapus
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void txt_searchKeyTyped(KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        searchData(); // Memanggil fungsi searchData() untuk mencari data berdasarkan kata kunci
    }//GEN-LAST:event_txt_searchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_ButtonRounded btn_batal;
    private Custom_ButtonRounded btn_before;
    private Custom_ButtonRounded btn_cancel;
    private Custom_ButtonRounded btn_first;
    private Custom_ButtonRounded btn_hapus;
    private Custom_ButtonRounded btn_last;
    private Custom_ButtonRounded btn_next;
    private Custom_ButtonRounded btn_simpan;
    private Custom_ButtonRounded btn_tambah;
    private JComboBox<String> cbx_data;
    private JPanel data_pelanggan;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JLabel lb_halaman;
    private JPanel main_panel;
    private ButtonGroup rbJenisKelamin;
    private JRadioButton rb_laki;
    private JRadioButton rb_perempuan;
    private JPanel tambah_pelanggan;
    private JTable_Custom tbl_data;
    private JTextfieldRounded txt_alamat;
    private JTextfieldRounded txt_id;
    private JTextfieldRounded txt_nama;
    private JTextfieldRounded txt_nohp;
    private JTextfieldRounded txt_search;
    // End of variables declaration//GEN-END:variables

    // paginationPelanggan() - Mengatur fungsi pagination untuk pelanggan
    private void paginationPelanggan() {
        // Mengatur tombol halaman pertama
        btn_first.addActionListener(e -> {
            HalamanSaatIni = 1;// Set ke halaman pertama
            loadData(); // Memuat data pada halaman pertama
        });

        // Mengatur tombol halaman sebelumnya
        btn_before.addActionListener(e -> {
            if (HalamanSaatIni > 1) {// Memastikan halaman saat ini lebih dari 1
                HalamanSaatIni--; // Turun ke halaman sebelumnya
                loadData();// Memuat data pada halaman saat ini
            }
        });

        // Mengatur combo box untuk jumlah data per halaman
        cbx_data.addActionListener(e -> {
            DataperHalaman = Integer.parseInt(cbx_data.getSelectedItem().toString());// Mengambil jumlah data per halaman dari combo box
            HalamanSaatIni = 1;// Set ke halaman pertama setiap kali data per halaman diubah
            loadData(); //Memuat data
        });

        // Mengatur tombol halaman berikutnya
        btn_next.addActionListener(e -> {
            if (HalamanSaatIni < totalpages) {// Memastikan belum di halaman terakhir
                HalamanSaatIni++;// Naik ke halaman berikutnya
                loadData();//Memuat data pada halaman baru
            }
        });

        // Mengatur tombol halaman terakhir
        btn_last.addActionListener(e -> {
            HalamanSaatIni = totalpages;// Set ke halaman terakhir
            loadData();// Memuat data pada halaman terakhir
        });
    }

    // calculateTotalPage() - Menghitung total halaman berdasarkan jumlah data dan data per halaman
    private void calculateTotalPage() {
        int totalData = getTotalData();// Mendapatkan total data pelanggan
        totalpages = (int) Math.ceil((double) totalData / DataperHalaman);// Menghitung total halaman
    }

    // getTotalData() - Mendapatkan total data pelanggan dari database
    private int getTotalData() {
        int totalData = 0;
        try {
            String sql = "SELECT COUNT(*) AS total FROM tbl_pelanggan";// Query menghitung total data pelanggan
            try (PreparedStatement st = con.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery(); // Eksekusi query
                if (rs.next()) {
                    totalData = rs.getInt("total");// Mendapatkan jumlah total dari kolom "total"
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);
        }
        return totalData;// Mengembalikan jumlah data
    }

    // loadData() - Memuat data pelanggan ke dalam JTable berdasarkan halaman saat ini
    private void loadData() {
        calculateTotalPage();// Menghitung total halaman
        int totalData = getTotalData();// Mendapatkan total data pelanggan
        lb_halaman.setText(String.valueOf("Halaman " + HalamanSaatIni + " Dari total data " + totalData)); // Menampilkan halaman saat ini

        int startIndex = (HalamanSaatIni - 1) * DataperHalaman;// Menentukan indeks awal data berdasarkan halaman saat ini
        getData(startIndex, DataperHalaman, (DefaultTableModel) tbl_data.getModel());// Mendapatkan data untuk ditampilkan di tabel
        btn_hapus.setVisible(false); // Menyembunyikan tombol hapus
        btn_cancel.setVisible(false); // Menyembunyikan tombol batal
    }

    // showPanel() - Mengatur tampilan panel utama
    private void showPanel() {
        main_panel.removeAll();// Menghapus semua komponen di panel utama
        main_panel.add(new Form_Pelanggan());// Menambahkan panel MenuPelanggan ke panel utama
        main_panel.repaint();// Menggambar ulang panel utama
        main_panel.revalidate();// Memastikan perubahan diterapkan
    }

    // resetForm() - Mengosongkan input form pelanggan
    private void resetForm() {
        txt_id.setText("");
        txt_nama.setText("");
        rbJenisKelamin.clearSelection(); // Mengosongkan pilihan jenis kelamin pada radio button
        txt_nohp.setText("");
        txt_alamat.setText("");
    }

    // setTabelModel() - Mengatur model tabel dengan kolom-kolom yang sesuai
    private void setTabelModel() {
        String[] columnNames = {
            "ID",
            "Nama",
            "Jenis Kelamin",
            "No.Hp",
            "Alamat"
        };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Membuat model tabel dengan kolom yang ditentukan
        tbl_data.setModel(model); // Mengatur model tabel untuk JTable
        loadData(); // Memuat data ke dalam tabel
    }

    // getData() - Mendapatkan data pelanggan dari database dengan batasan jumlah data per halaman
    private void getData(int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0); // Mengosongkan data yang ada di tabel

        try {
            String sql = "SELECT * FROM tbl_pelanggan LIMIT ?,?"; // Query dengan limit berdasarkan halaman
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setInt(1, startIndex); // Indeks awal
                st.setInt(2, entriesPage); // Jumlah data per halaman
                ResultSet rs = st.executeQuery(); // Eksekusi query

                while (rs.next()) {
                    String IdPelanggan = rs.getString("ID_Pelanggan");
                    String NamaPelanggan = rs.getString("Nama_Pelanggan");
                    String JkPelanggan = rs.getString("Jenis_Kelamin");
                    String TeleponPelanggan = rs.getString("No_Hp");
                    String AlamatPelanggan = rs.getString("Alamat");

                    Object[] rowData = {IdPelanggan, NamaPelanggan, JkPelanggan, TeleponPelanggan, AlamatPelanggan}; // Data pelanggan
                    model.addRow(rowData); // Menambahkan baris data ke dalam tabel
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);

        }
    }

    // setIDPelanggan() - Mengatur ID pelanggan secara otomatis
    private String setIDPelanggan() throws SQLException {
        String urutan = null;
        Date now = new Date();
        SimpleDateFormat noFormat = new SimpleDateFormat("yyMM"); // Format tanggal sebagai bagian dari ID
        String no = noFormat.format(now);

        String sql = "SELECT RIGHT(ID_Pelanggan, 3) AS Nomor FROM tbl_pelanggan WHERE ID_Pelanggan LIKE '" + no + "%' ORDER BY ID_Pelanggan DESC LIMIT 1";

        try (PreparedStatement st = con.prepareStatement(sql)) {
            ResultSet rs = st.executeQuery(); // Eksekusi query

            if (rs.next()) {
                int nomor = Integer.parseInt(rs.getString("nomor")) + 1; // Menambah nomor urut
                urutan = no + String.format("%03d", nomor); // Format ID baru
            } else {
                urutan = no + "001"; // ID awal jika tidak ada data
            }
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);
        }
        return urutan;
    }

    // insertData() - Menambahkan data pelanggan ke database
    private void insertData() {
        String IdPelanggan = txt_id.getText();
        String NamaPelanggan = txt_nama.getText();
        String JkPelanggan = rb_laki.isSelected() ? rb_laki.getText() : rb_perempuan.isSelected() ? rb_perempuan.getText() : "";
        String TeleponPelanggan = txt_nohp.getText();
        String AlamatPelanggan = txt_alamat.getText();

        // Validasi input data
        if (IdPelanggan.isEmpty() || NamaPelanggan.isEmpty() || JkPelanggan.isEmpty() || TeleponPelanggan.isEmpty()
                || AlamatPelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Insert data ke database
        try {
            String sql = "INSERT INTO tbl_pelanggan (ID_Pelanggan, Nama_Pelanggan, Jenis_Kelamin, No_Hp, Alamat) VALUES (?,?,?,?,?)";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, IdPelanggan);
                st.setString(2, NamaPelanggan);
                st.setString(3, JkPelanggan);
                st.setString(4, TeleponPelanggan);
                st.setString(5, AlamatPelanggan);

                int rowInserted = st.executeUpdate();// Menjalankan perintah insert
                if (rowInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                    resetForm(); // Kosongkan text field setelah data berhasil ditambahkan
                    loadData();  // Memuat data ke tampilan JTable atau komponen lainnya
                    showPanel();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // dataTabel() - Menampilkan data pelanggan dari JTable ke dalam form untuk diperbarui
    private void dataTabel() {
        data_pelanggan.setVisible(false); // Menyembunyikan panel view
        tambah_pelanggan.setVisible(true); // Menampilkan panel tambah/edit

        int row = tbl_data.getSelectedRow(); // Mendapatkan baris yang dipilih pada tabel
        jLabel2.setText("Perbarui Data"); // Mengubah teks label menjadi "PERBARUI DATA PELANGGAN"
        txt_id.setEnabled(false); // Menonaktifkan field ID pelanggan agar tidak bisa diedit

        // Mengisi field form dengan data dari baris yang dipilih
        txt_id.setText(tbl_data.getValueAt(row, 0).toString());
        txt_nama.setText(tbl_data.getValueAt(row, 1).toString());

        // Menentukan jenis kelamin dari data di tabel
        String jenisKelamin = tbl_data.getValueAt(row, 2).toString();
        if (jenisKelamin.equals("Laki - Laki")) {
            rb_laki.setSelected(true);// Memilih radio button Laki - Laki jika data di tabel sama
        } else if (jenisKelamin.equals("Perempuan")) {
            rb_perempuan.setSelected(true);// Memilih radio button Perempuan jika data di tabel sama
        }

        txt_nohp.setText(tbl_data.getValueAt(row, 3).toString());
        txt_alamat.setText(tbl_data.getValueAt(row, 4).toString());// Mengisi field alamat dengan data dari tabel
    }

    // updateData() - Memperbarui data pelanggan di database
    private void updateData() {
        // Mengambil data dari form
        String IdPelanggan = txt_id.getText();
        String NamaPelanggan = txt_nama.getText();
        String JkPelanggan = rb_laki.isSelected() ? rb_laki.getText() : rb_perempuan.isSelected() ? rb_perempuan.getText() : "";
        String TeleponPelanggan = txt_nohp.getText();
        String AlamatPelanggan = txt_alamat.getText();

        // Validasi input data
        if (IdPelanggan.isEmpty() || NamaPelanggan.isEmpty() || JkPelanggan.isEmpty() || TeleponPelanggan.isEmpty()
                || AlamatPelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Insert data ke database
        try {
            String sql = "UPDATE tbl_pelanggan SET Nama_Pelanggan=?, Jenis_Kelamin=?, No_Hp=?, Alamat=? WHERE ID_Pelanggan=?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, NamaPelanggan);
                st.setString(2, JkPelanggan);
                st.setString(3, TeleponPelanggan);
                st.setString(4, AlamatPelanggan);
                st.setString(5, IdPelanggan);

                int rowUpdated = st.executeUpdate();
                if (rowUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
                    resetForm();// Kosongkan form
                    loadData();  // Refresh data di JTable
                    showPanel(); // Tampilkan panel utama
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // hapusData() - Menghapus data pelanggan dari database
    private void hapusData() {
        int row = tbl_data.getSelectedRow();// Mendapatkan baris yang dipilih
        String IdPelanggan = tbl_data.getValueAt(row, 0).toString();// Mendapatkan ID pelanggan dari baris yang dipilih

        // Konfirmasi penghapusan
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM tbl_pelanggan WHERE ID_Pelanggan=?";
                try (PreparedStatement st = con.prepareStatement(sql)) {
                    st.setString(1, IdPelanggan);

                    int rowDeleted = st.executeUpdate();// Eksekusi penghapusan
                    if (rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                        loadData();// Refresh data di JTable
                    }
                }
            } catch (SQLException e) {
                Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }

    // searchData() - Mencari data pelanggan berdasarkan nama atau alamat
    private void searchData() {
        String kataKunci = txt_search.getText(); // Mengambil kata kunci dari text field pencarian

        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);// Mengosongkan data di tabel sebelum memuat hasil pencarian

        try {
            String sql = "SELECT * FROM tbl_pelanggan WHERE Nama_Pelanggan LIKE ? OR Alamat LIKE ?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, "%" + kataKunci + "%"); // Parameter pencarian pada kolom Nama
                st.setString(2, "%" + kataKunci + "%");// Parameter pencarian pada kolom Alamat

                ResultSet rs = st.executeQuery();

                while (rs.next()) {
                    String IdPelanggan = rs.getString("ID_Pelanggan");
                    String NamaPelanggan = rs.getString("Nama_Pelanggan");
                    String JkPelanggan = rs.getString("Jenis_Kelamin");
                    String TeleponPelanggan = rs.getString("No_Hp");
                    String AlamatPelanggan = rs.getString("Alamat");

                    Object[] rowData = {IdPelanggan, NamaPelanggan, JkPelanggan, TeleponPelanggan, AlamatPelanggan};
                    model.addRow(rowData);// Tambahkan hasil pencarian ke dalam JTable
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Form_Pelanggan.class.getName()).log(Level.SEVERE, null, e);

        }
    }
}
