/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import java.time.LocalDate;
import Config.Koneksi_dua;
import Palette.Custom_ButtonRounded;
import Palette.JTable_Custom;
import Palette.JTextfieldRounded;
import Palette.Panelcustom;
import com.raven.datechooser.DateChooser;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SwingUtilities;
import javax.swing.border.BevelBorder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mahar
 */
public class Laporan_Penjualan extends javax.swing.JPanel {

    /**
     * Creates new form Form_Pelanggan
     */
    private int HalamanSaatIni = 1;
    private int DataperHalaman = 14;
    private int totalpages;
    private boolean isDataLoaded = false; // Untuk melacak apakah data sudah ditampilkan
    private final Connection con;// Koneksi database

    private String userID;

    public Laporan_Penjualan(String userID) {
        con = Koneksi_dua.con(); // Membuat koneksi ke database
        this.userID = userID;
        initComponents(); // Inisialisasi komponen GUI
        setDefaultDate(); // Pastikan tanggal default diatur sebelum load
        setTabelModel();
        actionButton();
        paginationKonsol();
        setPendapatan();
        txt_tanggal.setEditable(false); // Opsional: agar tidak bisa diedit manual
        // Listener untuk tombol kalender
    }

    private void setColumnWidth() {
//        TableColumnModel columnModel = tbl_data.getColumnModel();
//        columnModel.getColumn(0).setPreferredWidth(40);
//        columnModel.getColumn(0).setMaxWidth(40);
//        columnModel.getColumn(0).setMinWidth(40);
//
//        TableColumnModel columnModel2 = tbl_data_detail.getColumnModel();
//        columnModel2.getColumn(0).setPreferredWidth(40);
//        columnModel2.getColumn(0).setMaxWidth(40);
//        columnModel2.getColumn(0).setMinWidth(40);

        TableColumnModel columnModel3 = tbl_data_sementara.getColumnModel();
        columnModel3.getColumn(0).setPreferredWidth(40);
        columnModel3.getColumn(0).setMaxWidth(40);
        columnModel3.getColumn(0).setMinWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new DateChooser();
        main_panel = new JPanel();
        data_pelanggan = new JPanel();
        jLabel1 = new JLabel();
        btn_tampilkan = new Custom_ButtonRounded();
        jScrollPane1 = new JScrollPane();
        tbl_data = new JTable_Custom();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        btn_first = new Custom_ButtonRounded();
        btn_before = new Custom_ButtonRounded();
        cbx_data = new JComboBox<>();
        btn_next = new Custom_ButtonRounded();
        btn_last = new Custom_ButtonRounded();
        lb_halaman = new JLabel();
        txt_search = new JTextfieldRounded();
        btn_cetak = new Custom_ButtonRounded();
        panelcustom11 = new Panelcustom();
        Pendapatan = new JLabel();
        jLabel2 = new JLabel();
        txt_tanggal = new JTextfieldRounded();
        tambah_transaksi = new JPanel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        panelcustom1 = new Panelcustom();
        txt_tangal = new JTextfieldRounded();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        cbx_pelanggan = new JComboBox<>();
        panelcustom6 = new Panelcustom();
        cbx_meja = new JComboBox<>();
        jLabel14 = new JLabel();
        jLabel9 = new JLabel();
        panelcustom2 = new Panelcustom();
        txt_jumlah = new JTextfieldRounded();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        btn_set_barcode = new Custom_ButtonRounded();
        panelcustom5 = new Panelcustom();
        txt_barcode = new JTextfieldRounded();
        btn_ubah = new Custom_ButtonRounded();
        btn_cancel_sementara = new Custom_ButtonRounded();
        btn_hapus = new Custom_ButtonRounded();
        panelcustom3 = new Panelcustom();
        panelcustom4 = new Panelcustom();
        lb_ID = new JLabel();
        lb_total_beli = new JLabel();
        jLabel15 = new JLabel();
        lb_total_beli2 = new JLabel();
        jScrollPane2 = new JScrollPane();
        tbl_data_sementara = new JTable_Custom();
        panelcustom7 = new Panelcustom();
        txt_kembalian = new JTextfieldRounded();
        txt_bayar = new JTextfieldRounded();
        jLabel16 = new JLabel();
        jLabel17 = new JLabel();
        panelcustom10 = new Panelcustom();
        btn_simpan = new Custom_ButtonRounded();
        btn_batal_add = new Custom_ButtonRounded();
        panelcustom9 = new Panelcustom();
        panelcustom8 = new Panelcustom();
        jLabel19 = new JLabel();
        jScrollPane3 = new JScrollPane();
        txt_catatan = new JTextArea();

        setLayout(new CardLayout());

        main_panel.setLayout(new CardLayout());

        data_pelanggan.setBackground(new Color(255, 255, 255));

        jLabel1.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Laporan Data Penjualan");

        btn_tampilkan.setIcon(new ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N
        btn_tampilkan.setText("Tampilkan");
        btn_tampilkan.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_tampilkanActionPerformed(evt);
            }
        });

        tbl_data.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/Icons/Icon7.png"))); // NOI18N

        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Icons/Edit Graph Report.png"))); // NOI18N

        jLabel5.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/Icons/Sorting.png"))); // NOI18N
        jLabel5.setText(" >");

        btn_first.setText("First Page");
        btn_first.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_before.setText("<");
        btn_before.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_beforeActionPerformed(evt);
            }
        });

        cbx_data.setModel(new DefaultComboBoxModel<>(new String[] { "8", "16", "32", " " }));
        cbx_data.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cbx_dataActionPerformed(evt);
            }
        });

        btn_next.setText(">");
        btn_next.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_last.setText("Last Page");
        btn_last.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        lb_halaman.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        lb_halaman.setForeground(new Color(153, 153, 153));
        lb_halaman.setText("Halaman of Total Halaman");

        txt_search.setText("Search");
        txt_search.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        btn_cetak.setIcon(new ImageIcon(getClass().getResource("/Icons/Print1.png"))); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.setFillClick(new Color(102, 204, 255));
        btn_cetak.setFillOriginal(new Color(0, 204, 204));
        btn_cetak.setFillOver(new Color(0, 153, 153));

        panelcustom11.setBackground(new Color(204, 204, 204));
        panelcustom11.setRoundBottomRight(20);
        panelcustom11.setRoundBottomleft(20);
        panelcustom11.setRoundTopLeft(20);
        panelcustom11.setRoundTopRight(20);

        Pendapatan.setFont(new Font("SansSerif", 1, 36)); // NOI18N
        Pendapatan.setForeground(new Color(52, 152, 219));
        Pendapatan.setText("0");

        jLabel2.setBackground(new Color(255, 255, 255));
        jLabel2.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("Total Pendapatan");

        GroupLayout panelcustom11Layout = new GroupLayout(panelcustom11);
        panelcustom11.setLayout(panelcustom11Layout);
        panelcustom11Layout.setHorizontalGroup(panelcustom11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcustom11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(Pendapatan, GroupLayout.PREFERRED_SIZE, 310, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcustom11Layout.setVerticalGroup(panelcustom11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelcustom11Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pendapatan)
                .addContainerGap())
        );

        txt_tanggal.setText("Tanggal");
        txt_tanggal.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                txt_tanggalMouseClicked(evt);
            }
        });
        txt_tanggal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txt_tanggalActionPerformed(evt);
            }
        });
        txt_tanggal.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                txt_tanggalKeyTyped(evt);
            }
        });

        GroupLayout data_pelangganLayout = new GroupLayout(data_pelanggan);
        data_pelanggan.setLayout(data_pelangganLayout);
        data_pelangganLayout.setHorizontalGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelcustom11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(data_pelangganLayout.createSequentialGroup()
                        .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(data_pelangganLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(data_pelangganLayout.createSequentialGroup()
                                .addComponent(btn_tampilkan, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cetak, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                        .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                                .addComponent(txt_tanggal, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12))
            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                        .addComponent(lb_halaman)
                        .addGap(47, 47, 47))
                    .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                        .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)))
                .addGap(339, 339, 339))
        );
        data_pelangganLayout.setVerticalGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, data_pelangganLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tampilkan, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cetak, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanggal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelcustom11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_halaman)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(data_pelangganLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_before, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_data, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_last, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        main_panel.add(data_pelanggan, "card2");

        tambah_transaksi.setBackground(new Color(255, 255, 255));

        jLabel6.setIcon(new ImageIcon(getClass().getResource("/Icons/Transaksi.png"))); // NOI18N

        jLabel7.setIcon(new ImageIcon(getClass().getResource("/Icons/Transaksi.png"))); // NOI18N

        jLabel8.setFont(new Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/Icons/Sorting.png"))); // NOI18N
        jLabel8.setText(" >");

        panelcustom1.setRoundBottomRight(20);
        panelcustom1.setRoundBottomleft(20);
        panelcustom1.setRoundTopLeft(20);
        panelcustom1.setRoundTopRight(20);

        txt_tangal.setText("Tanggal");

        jLabel10.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel10.setText("Tanggal");

        jLabel11.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel11.setText("Pelanggan");

        cbx_pelanggan.setFont(new Font("SansSerif", 0, 12)); // NOI18N
        cbx_pelanggan.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelcustom6.setBackground(new Color(52, 152, 219));
        panelcustom6.setRoundBottomRight(20);
        panelcustom6.setRoundBottomleft(20);
        panelcustom6.setRoundTopLeft(20);
        panelcustom6.setRoundTopRight(20);

        GroupLayout panelcustom6Layout = new GroupLayout(panelcustom6);
        panelcustom6.setLayout(panelcustom6Layout);
        panelcustom6Layout.setHorizontalGroup(panelcustom6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelcustom6Layout.setVerticalGroup(panelcustom6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        cbx_meja.setFont(new Font("SansSerif", 0, 12)); // NOI18N
        cbx_meja.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel14.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel14.setText("Meja");

        GroupLayout panelcustom1Layout = new GroupLayout(panelcustom1);
        panelcustom1.setLayout(panelcustom1Layout);
        panelcustom1Layout.setHorizontalGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelcustom6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelcustom1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx_pelanggan, 0, 142, Short.MAX_VALUE)
                    .addComponent(txt_tangal, GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(cbx_meja, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelcustom1Layout.setVerticalGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom1Layout.createSequentialGroup()
                .addComponent(panelcustom6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tangal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_pelanggan, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelcustom1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_meja, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setText("Tambah Data");

        panelcustom2.setRoundBottomRight(20);
        panelcustom2.setRoundBottomleft(20);
        panelcustom2.setRoundTopLeft(20);
        panelcustom2.setRoundTopRight(20);

        txt_jumlah.setText("Qty");

        jLabel12.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel12.setText("Barcode");

        jLabel13.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setText("Qty");

        btn_set_barcode.setText("...");

        panelcustom5.setBackground(new Color(52, 152, 219));
        panelcustom5.setRoundBottomRight(20);
        panelcustom5.setRoundBottomleft(20);
        panelcustom5.setRoundTopLeft(20);
        panelcustom5.setRoundTopRight(20);

        GroupLayout panelcustom5Layout = new GroupLayout(panelcustom5);
        panelcustom5.setLayout(panelcustom5Layout);
        panelcustom5Layout.setHorizontalGroup(panelcustom5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelcustom5Layout.setVerticalGroup(panelcustom5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        txt_barcode.setText("Barcode");

        btn_ubah.setIcon(new ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N

        btn_cancel_sementara.setIcon(new ImageIcon(getClass().getResource("/Icons/Close5.png"))); // NOI18N
        btn_cancel_sementara.setFillClick(new Color(153, 51, 0));
        btn_cancel_sementara.setFillOriginal(new Color(255, 153, 51));
        btn_cancel_sementara.setFillOver(new Color(204, 102, 0));
        btn_cancel_sementara.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_cancel_sementaraActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        btn_hapus.setFillClick(new Color(153, 0, 51));
        btn_hapus.setFillOriginal(new Color(255, 0, 51));
        btn_hapus.setFillOver(new Color(204, 0, 51));
        btn_hapus.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        GroupLayout panelcustom2Layout = new GroupLayout(panelcustom2);
        panelcustom2.setLayout(panelcustom2Layout);
        panelcustom2Layout.setHorizontalGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelcustom5, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelcustom2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustom2Layout.createSequentialGroup()
                        .addComponent(btn_ubah, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel_sementara, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelcustom2Layout.createSequentialGroup()
                        .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelcustom2Layout.createSequentialGroup()
                                .addComponent(txt_barcode, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_set_barcode, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_jumlah, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelcustom2Layout.setVerticalGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom2Layout.createSequentialGroup()
                .addComponent(panelcustom5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustom2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_set_barcode, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_barcode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelcustom2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelcustom2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_jumlah, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelcustom2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cancel_sementara, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ubah, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hapus, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        panelcustom3.setRoundBottomRight(20);
        panelcustom3.setRoundBottomleft(20);
        panelcustom3.setRoundTopLeft(20);
        panelcustom3.setRoundTopRight(20);

        panelcustom4.setBackground(new Color(52, 152, 219));
        panelcustom4.setRoundBottomRight(20);
        panelcustom4.setRoundBottomleft(20);
        panelcustom4.setRoundTopLeft(20);
        panelcustom4.setRoundTopRight(20);

        GroupLayout panelcustom4Layout = new GroupLayout(panelcustom4);
        panelcustom4.setLayout(panelcustom4Layout);
        panelcustom4Layout.setHorizontalGroup(panelcustom4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelcustom4Layout.setVerticalGroup(panelcustom4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        lb_ID.setBackground(new Color(52, 152, 219));
        lb_ID.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        lb_ID.setForeground(new Color(52, 152, 219));
        lb_ID.setText("ID");

        lb_total_beli.setFont(new Font("SansSerif", 1, 48)); // NOI18N
        lb_total_beli.setForeground(new Color(52, 152, 219));
        lb_total_beli.setText("Rp.");

        jLabel15.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel15.setText("ID");

        lb_total_beli2.setFont(new Font("SansSerif", 1, 48)); // NOI18N
        lb_total_beli2.setForeground(new Color(52, 152, 219));
        lb_total_beli2.setText("Total Beli");

        GroupLayout panelcustom3Layout = new GroupLayout(panelcustom3);
        panelcustom3.setLayout(panelcustom3Layout);
        panelcustom3Layout.setHorizontalGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelcustom4, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelcustom3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustom3Layout.createSequentialGroup()
                        .addComponent(lb_total_beli)
                        .addGap(18, 18, 18)
                        .addComponent(lb_total_beli2, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelcustom3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lb_ID, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcustom3Layout.setVerticalGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom3Layout.createSequentialGroup()
                .addComponent(panelcustom4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ID, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelcustom3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lb_total_beli2, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_total_beli, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tbl_data_sementara.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_data_sementara);

        panelcustom7.setRoundBottomRight(20);
        panelcustom7.setRoundBottomleft(20);
        panelcustom7.setRoundTopLeft(20);
        panelcustom7.setRoundTopRight(20);

        txt_kembalian.setText("Kembalian");

        txt_bayar.setText("Bayar");

        jLabel16.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel16.setText("Kembalian");

        jLabel17.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel17.setText("Bayar");

        panelcustom10.setBackground(new Color(52, 152, 219));
        panelcustom10.setRoundBottomRight(20);
        panelcustom10.setRoundBottomleft(20);
        panelcustom10.setRoundTopLeft(20);
        panelcustom10.setRoundTopRight(20);

        GroupLayout panelcustom10Layout = new GroupLayout(panelcustom10);
        panelcustom10.setLayout(panelcustom10Layout);
        panelcustom10Layout.setHorizontalGroup(panelcustom10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        panelcustom10Layout.setVerticalGroup(panelcustom10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        GroupLayout panelcustom7Layout = new GroupLayout(panelcustom7);
        panelcustom7.setLayout(panelcustom7Layout);
        panelcustom7Layout.setHorizontalGroup(panelcustom7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelcustom7Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelcustom7Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelcustom7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(56, 56, 56)
                        .addComponent(txt_bayar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelcustom7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txt_kembalian, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addComponent(panelcustom10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelcustom7Layout.setVerticalGroup(panelcustom7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom7Layout.createSequentialGroup()
                .addComponent(panelcustom10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelcustom7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kembalian, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelcustom7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bayar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btn_simpan.setIcon(new ImageIcon(getClass().getResource("/Icons/Paper Plane.png"))); // NOI18N
        btn_simpan.setText(" Simpan");
        btn_simpan.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal_add.setIcon(new ImageIcon(getClass().getResource("/Icons/Icon5.png"))); // NOI18N
        btn_batal_add.setText(" Reset");
        btn_batal_add.setFillClick(new Color(153, 51, 0));
        btn_batal_add.setFillOriginal(new Color(255, 153, 51));
        btn_batal_add.setFillOver(new Color(204, 102, 0));

        panelcustom9.setRoundBottomRight(20);
        panelcustom9.setRoundBottomleft(20);
        panelcustom9.setRoundTopLeft(20);
        panelcustom9.setRoundTopRight(20);

        panelcustom8.setBackground(new Color(52, 152, 219));
        panelcustom8.setRoundBottomRight(20);
        panelcustom8.setRoundBottomleft(20);
        panelcustom8.setRoundTopLeft(20);
        panelcustom8.setRoundTopRight(20);

        GroupLayout panelcustom8Layout = new GroupLayout(panelcustom8);
        panelcustom8.setLayout(panelcustom8Layout);
        panelcustom8Layout.setHorizontalGroup(panelcustom8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelcustom8Layout.setVerticalGroup(panelcustom8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel19.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel19.setText("Catatan");

        txt_catatan.setColumns(20);
        txt_catatan.setFont(new Font("SansSerif", 0, 12)); // NOI18N
        txt_catatan.setRows(5);
        txt_catatan.setBorder(null);
        jScrollPane3.setViewportView(txt_catatan);

        GroupLayout panelcustom9Layout = new GroupLayout(panelcustom9);
        panelcustom9.setLayout(panelcustom9Layout);
        panelcustom9Layout.setHorizontalGroup(panelcustom9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelcustom8, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, panelcustom9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 222, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelcustom9Layout.setVerticalGroup(panelcustom9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom9Layout.createSequentialGroup()
                .addComponent(panelcustom8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelcustom9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelcustom9Layout.createSequentialGroup()
                        .addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        GroupLayout tambah_transaksiLayout = new GroupLayout(tambah_transaksi);
        tambah_transaksi.setLayout(tambah_transaksiLayout);
        tambah_transaksiLayout.setHorizontalGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, tambah_transaksiLayout.createSequentialGroup()
                .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(tambah_transaksiLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(GroupLayout.Alignment.LEADING, tambah_transaksiLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(tambah_transaksiLayout.createSequentialGroup()
                                .addComponent(panelcustom1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelcustom2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelcustom3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(tambah_transaksiLayout.createSequentialGroup()
                                .addComponent(panelcustom7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(panelcustom9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_batal_add, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
                                .addGap(149, 149, 149)))))
                .addGap(12, 12, 12))
            .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(tambah_transaksiLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel9)
                    .addContainerGap(957, Short.MAX_VALUE)))
        );
        tambah_transaksiLayout.setVerticalGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tambah_transaksiLayout.createSequentialGroup()
                .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_transaksiLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addGroup(GroupLayout.Alignment.TRAILING, tambah_transaksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelcustom2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelcustom1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelcustom3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_transaksiLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_batal_add, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_simpan, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelcustom9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelcustom7, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(tambah_transaksiLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(tambah_transaksiLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel9)
                    .addContainerGap(536, Short.MAX_VALUE)))
        );

        main_panel.add(tambah_transaksi, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tampilkanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_tampilkanActionPerformed

    }//GEN-LAST:event_btn_tampilkanActionPerformed

    private void btn_firstActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_beforeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_beforeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_beforeActionPerformed

    private void btn_nextActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lastActionPerformed

    private void cbx_dataActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cbx_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_dataActionPerformed

    private void tbl_dataMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked

    }//GEN-LAST:event_tbl_dataMouseClicked

    private void txt_searchKeyTyped(KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
    }//GEN-LAST:event_txt_searchKeyTyped

    private void btn_cancel_sementaraActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_cancel_sementaraActionPerformed

    }//GEN-LAST:event_btn_cancel_sementaraActionPerformed

    private void btn_hapusActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_simpanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_tanggalKeyTyped(KeyEvent evt) {//GEN-FIRST:event_txt_tanggalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalKeyTyped

    private void txt_tanggalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txt_tanggalActionPerformed

    }//GEN-LAST:event_txt_tanggalActionPerformed

    private void txt_tanggalMouseClicked(MouseEvent evt) {//GEN-FIRST:event_txt_tanggalMouseClicked
        showDateChooser();
    }//GEN-LAST:event_txt_tanggalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel Pendapatan;
    private Custom_ButtonRounded btn_batal_add;
    private Custom_ButtonRounded btn_before;
    private Custom_ButtonRounded btn_cancel_sementara;
    private Custom_ButtonRounded btn_cetak;
    private Custom_ButtonRounded btn_first;
    private Custom_ButtonRounded btn_hapus;
    private Custom_ButtonRounded btn_last;
    private Custom_ButtonRounded btn_next;
    private Custom_ButtonRounded btn_set_barcode;
    private Custom_ButtonRounded btn_simpan;
    private Custom_ButtonRounded btn_tampilkan;
    private Custom_ButtonRounded btn_ubah;
    private JComboBox<String> cbx_data;
    private JComboBox<String> cbx_meja;
    private JComboBox<String> cbx_pelanggan;
    private JPanel data_pelanggan;
    private DateChooser dateChooser;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JLabel lb_ID;
    private JLabel lb_halaman;
    private JLabel lb_total_beli;
    private JLabel lb_total_beli2;
    private JPanel main_panel;
    private Panelcustom panelcustom1;
    private Panelcustom panelcustom10;
    private Panelcustom panelcustom11;
    private Panelcustom panelcustom2;
    private Panelcustom panelcustom3;
    private Panelcustom panelcustom4;
    private Panelcustom panelcustom5;
    private Panelcustom panelcustom6;
    private Panelcustom panelcustom7;
    private Panelcustom panelcustom8;
    private Panelcustom panelcustom9;
    private JPanel tambah_transaksi;
    private JTable_Custom tbl_data;
    private JTable_Custom tbl_data_sementara;
    private JTextfieldRounded txt_barcode;
    private JTextfieldRounded txt_bayar;
    private JTextArea txt_catatan;
    private JTextfieldRounded txt_jumlah;
    private JTextfieldRounded txt_kembalian;
    private JTextfieldRounded txt_search;
    private JTextfieldRounded txt_tangal;
    private JTextfieldRounded txt_tanggal;
    // End of variables declaration//GEN-END:variables
private void showDateChooser() {
        JDialog dialog = new JDialog();
        dialog.setTitle("Pilih Tanggal");
        dialog.setModal(true);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        // Inisialisasi JDateChooser
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDateFormatString("yyyy-MM-dd");

        // Batasi tanggal hingga hari ini (27 Mei 2025, 06:56 PM WIB)
        dateChooser.setMaxSelectableDate(new Date(System.currentTimeMillis()));

        // Jika txt_tanggal sudah memiliki nilai, set tanggal awal di JDateChooser
        try {
            String tanggalStr = txt_tanggal.getText().trim();
            if (!tanggalStr.isEmpty() && tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                dateChooser.setDate(dateFormat.parse(tanggalStr));
            }
        } catch (ParseException e) {
            Logger.getLogger(Laporan_Penjualan.class.getName()).log(Level.SEVERE, null, e);
        }

        // Tombol OK untuk konfirmasi
        JButton btnOk = new JButton("OK");
        btnOk.setBackground(new Color(46, 204, 113)); // Warna hijau
        btnOk.setForeground(Color.WHITE);
        btnOk.addActionListener(e -> {
            if (dateChooser.getDate() != null) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                txt_tanggal.setText(dateFormat.format(dateChooser.getDate()));
                isDataLoaded = false; // Reset status saat tanggal berubah
            }
            dialog.dispose();
        });

        // Tombol Batal untuk membatalkan
        JButton btnCancel = new JButton("Batal");
        btnCancel.setBackground(new Color(231, 76, 60)); // Warna merah
        btnCancel.setForeground(Color.WHITE);
        btnCancel.addActionListener(e -> dialog.dispose());

        // Panel untuk layout
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Padding
        panel.add(dateChooser, BorderLayout.CENTER);

        // Panel untuk tombol
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttonPanel.add(btnOk);
        buttonPanel.add(btnCancel);
        panel.add(buttonPanel, BorderLayout.SOUTH);

        dialog.add(panel);
        dialog.pack(); // Menyesuaikan ukuran awal berdasarkan konten
        dialog.setSize(300, 150); // Atur lebar (300px) dan tinggi (200px) secara manual
        dialog.setLocationRelativeTo(null); // Posisikan di tengah
        dialog.setVisible(true);
    }

// Tidak set tanggal default, biarkan kosong agar user harus memilih
    private void setDefaultDate() {
        txt_tanggal.setText(""); // Kosongkan field agar user harus memilih
    }

    private void paginationKonsol() {
        btn_first.addActionListener(e -> {
            HalamanSaatIni = 1;
            load();
        });

        btn_before.addActionListener(e -> {
            if (HalamanSaatIni > 1) {
                HalamanSaatIni--;
                load();
            }
        });

        cbx_data.addActionListener(e -> {
            DataperHalaman = Integer.parseInt(cbx_data.getSelectedItem().toString());
            HalamanSaatIni = 1;
            load();
        });

        btn_next.addActionListener(e -> {
            if (HalamanSaatIni < totalpages) {
                HalamanSaatIni++;
                load();
            }
        });

        btn_last.addActionListener(e -> {
            HalamanSaatIni = totalpages;
            load();
        });
    }

    private void actionButton() {
        btn_tampilkan.addActionListener(e -> {
            String tanggalStr = txt_tanggal.getText().trim();
            if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(null, "Silakan pilih tanggal terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            isDataLoaded = true; // Set flag saat tombol Tampilkan diklik
            load();
        });

        btn_cetak.addActionListener(e -> {
            String tanggalStr = txt_tanggal.getText().trim();
            if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(null, "Silakan pilih tanggal terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!isDataLoaded) {
                JOptionPane.showMessageDialog(null, "Silakan tampilkan data terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            // Periksa apakah ada data sebelum mencetak
            if (((DefaultTableModel) tbl_data.getModel()).getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data untuk dicetak!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            cetakLaporan();
        });

        txt_search.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String tanggalStr = txt_tanggal.getText().trim();
                if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
                    JOptionPane.showMessageDialog(null, "Silakan pilih tanggal terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                isDataLoaded = true; // Set flag saat mencari data
                searchData();
            }
        });
    }

    private int getTotalData() {
        int totalData = 0;
        String tanggalStr = txt_tanggal.getText().trim();
        if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            return 0; // Kembalikan 0 jika tanggal tidak valid
        }

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = dateFormat.parse(tanggalStr);
            String sql = "SELECT COUNT(*) AS total FROM tbl_transaksi WHERE DATE(Tanggal_Transaksi) = ?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setDate(1, new java.sql.Date(tanggal.getTime()));
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    totalData = rs.getInt("total");
                }
            }
        } catch (SQLException | ParseException e) {
            Logger.getLogger(Laporan_Penjualan.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Gagal menghitung total data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return totalData;
    }

    private void calculateTotalPages() {
        int totalData = getTotalData();
        totalpages = (int) Math.ceil((double) totalData / DataperHalaman);
    }

    private void ShowPanel() {
        main_panel.removeAll();
        main_panel.add(new Laporan_Penjualan(userID));
        main_panel.repaint();
        main_panel.revalidate();
    }

    private void load() {
        String tanggalStr = txt_tanggal.getText().trim();
        if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            // Hanya tampilkan pesan validasi jika dipicu oleh aksi pengguna (misalnya, tombol Tampilkan)
            if (isDataLoaded) {
                JOptionPane.showMessageDialog(null, "Silakan pilih tanggal terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
            return;
        }

        calculateTotalPages();
        int totalData = getTotalData();
        lb_halaman.setText("Halaman " + HalamanSaatIni + " dari Total Data " + totalData);

        int startIndex = (HalamanSaatIni - 1) * DataperHalaman;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        try {
            Date tanggal = dateFormat.parse(tanggalStr);
            DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
            getData(tanggal, startIndex, DataperHalaman, model);

            // Periksa apakah data kosong
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data untuk tanggal ini!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                Pendapatan.setText("Rp 0");
                return;
            }

            setPendapatan();
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal tidak valid! Gunakan format yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setTabelModel() {
        String[] columnNames = {
            "ID_Transaksi", "Tanggal Transaksi", "Nama Pelanggan", "Total Harga",
            "Nama User", "Nomor Meja"
        };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        tbl_data.setModel(model);
        // Tidak memanggil load() untuk mencegah validasi saat halaman dibuka
    }

    public void getData(Date tanggal, int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0);

        try {
            String sql = "SELECT tr.ID_Transaksi, tr.Tanggal_Transaksi, p.Nama_Pelanggan, tr.Total, "
                    + "u.Nama_User, m.Nomor_Meja "
                    + "FROM tbl_transaksi tr "
                    + "INNER JOIN tbl_pelanggan p ON tr.ID_Pelanggan = p.ID_Pelanggan "
                    + "INNER JOIN tbl_user u ON tr.ID_User = u.ID_User "
                    + "INNER JOIN tbl_meja m ON tr.ID_Meja = m.ID_Meja "
                    + "WHERE DATE(tr.Tanggal_Transaksi) = ? "
                    + "ORDER BY tr.Tanggal_Transaksi DESC LIMIT ?, ?";

            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setDate(1, new java.sql.Date(tanggal.getTime()));
                st.setInt(2, startIndex);
                st.setInt(3, entriesPage);

                ResultSet rs = st.executeQuery();

                int no = startIndex + 1;
                while (rs.next()) {
                    Object[] rowData = {
                        rs.getString("ID_Transaksi"),
                        rs.getString("Tanggal_Transaksi"),
                        rs.getString("Nama_Pelanggan"),
                        rs.getString("Total"),
                        rs.getString("Nama_User"),
                        rs.getString("Nomor_Meja")
                    };
                    model.addRow(rowData);

                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Laporan_Penjualan.class
                    .getName()).log(Level.SEVERE, null, e);
        }
    }

    private void searchData() {
        String tanggalStr = txt_tanggal.getText().trim();
        if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(null, "Silakan pilih tanggal terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String kataKunci = txt_search.getText();
        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = dateFormat.parse(tanggalStr);
            String sql = "SELECT tr.ID_Transaksi, tr.Tanggal_Transaksi, p.Nama_Pelanggan, tr.Total, "
                    + "u.Nama_User, m.Nomor_Meja "
                    + "FROM tbl_transaksi tr "
                    + "INNER JOIN tbl_pelanggan p ON tr.ID_Pelanggan = p.ID_Pelanggan "
                    + "INNER JOIN tbl_user u ON tr.ID_User = u.ID_User "
                    + "INNER JOIN tbl_meja m ON tr.ID_Meja = m.ID_Meja "
                    + "WHERE (p.Nama_Pelanggan LIKE ? OR tr.ID_Transaksi LIKE ? OR u.Nama_User LIKE ?) "
                    + "AND DATE(tr.Tanggal_Transaksi) = ? "
                    + "ORDER BY tr.Tanggal_Transaksi DESC";

            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");
                st.setString(3, "%" + kataKunci + "%");
                st.setDate(4, new java.sql.Date(tanggal.getTime()));
                ResultSet rs = st.executeQuery();

                while (rs.next()) {
                    Object[] rowData = {
                        rs.getString("ID_Transaksi"),
                        rs.getString("Tanggal_Transaksi"),
                        rs.getString("Nama_Pelanggan"),
                        rs.getString("Total"),
                        rs.getString("Nama_User"),
                        rs.getString("Nomor_Meja")
                    };
                    model.addRow(rowData);
                }

                // Periksa apakah hasil pencarian kosong
                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Tidak ada data yang sesuai dengan pencarian untuk tanggal ini!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException | ParseException e) {
            Logger.getLogger(Laporan_Penjualan.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Gagal melakukan pencarian: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cetakLaporan() {
        String tanggalStr = txt_tanggal.getText().trim();
        if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(null, "Silakan pilih tanggal terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!isDataLoaded) {
            JOptionPane.showMessageDialog(null, "Silakan tampilkan data terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String reportPath = "src/Report/Laporan_Penjualan.jasper";
        try {
            File file = new File(reportPath);
            if (!file.exists()) {
                JasperCompileManager.compileReportToFile("src/Report/Laporan_Penjualan.jrxml", reportPath);
            }

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            dateFormat.setLenient(false);
            Date tanggal = dateFormat.parse(tanggalStr);
            System.out.println("Tanggal yang dikirim: " + tanggal);

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("tanggal", tanggal);

            if (con == null || con.isClosed()) {
                throw new Exception("Koneksi database tidak valid atau telah ditutup");
            }

            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, con);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
            viewer.setVisible(true);
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Format tanggal salah. Gunakan format yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal mengisi laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setPendapatan() {
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            String tanggalStr = txt_tanggal.getText().trim();
            if (tanggalStr.isEmpty() || !tanggalStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
                Pendapatan.setText("Rp 0");
                return;
            }
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = dateFormat.parse(tanggalStr);
            String sql = "SELECT SUM(Total) AS total_pendapatan FROM tbl_transaksi WHERE DATE(Tanggal_Transaksi) = ?";
            pst = con.prepareStatement(sql);
            pst.setDate(1, new java.sql.Date(tanggal.getTime()));

            rs = pst.executeQuery();
            if (rs.next()) {
                double totalPendapatan = rs.getDouble("total_pendapatan");
                if (rs.wasNull()) {
                    totalPendapatan = 0.0;
                }
                Pendapatan.setText("Rp " + String.format("%,.0f", totalPendapatan));
            } else {
                Pendapatan.setText("Rp 0");
            }
        } catch (SQLException | ParseException e) {
            e.printStackTrace();
            Pendapatan.setText("Error!");
            JOptionPane.showMessageDialog(this, "Gagal menghitung pendapatan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
}
