/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

//import View.MenuDashboard;
//import View.MenuKategori;
//import View.MenuKonsol;
//import View.MenuLaporan;
//import View.MenuPelanggan;
//import View.MenuPengembalian;
//import View.MenuSewa;
//import View.MenuUser;
//import java.awt.Color;
import View.FormLogin;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Font;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mahar
 */
public class MenuUtama extends javax.swing.JFrame {

    int xx, xy;

    /**
     * Creates new form MenuUtama
     */
    private String userID;
    private String levelUser;
    private Timer timer;

    public MenuUtama(String userID, String namaUser, String levelUser) {
        initComponents();

        this.userID = userID;
        this.levelUser = levelUser;
        lb_nama.setText(namaUser);

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
//        Sidemenu.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        execute(userID, namaUser, levelUser);
        setDate();
    }

    private void setDate() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar calender = Calendar.getInstance();
                Date now = new Date();
                SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
                SimpleDateFormat formatTanggal = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                String hari = formatHari.format(calender.getTime());
                String waktuTanggal = formatTanggal.format(now);

                lb_date.setText(hari + "," + waktuTanggal);
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Sidemenu = new javax.swing.JPanel();
        pn_kanan = new javax.swing.JPanel();
        jPanelGradient1 = new Palette.JPanelGradient();
        lb_nama = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(223, 38));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kanyaah.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("SIRASA");

        jScrollPane1.setBorder(null);

        Sidemenu.setBackground(new java.awt.Color(255, 255, 255));
        Sidemenu.setLayout(new javax.swing.BoxLayout(Sidemenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(Sidemenu);

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        jPanelGradient1.setColorend(new java.awt.Color(0, 255, 255));
        jPanelGradient1.setColorstart(new java.awt.Color(204, 204, 240));

        lb_nama.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lb_nama.setForeground(new java.awt.Color(102, 102, 102));
        lb_nama.setText("Rumah Makan");

        lb_date.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_date.setText("Date");

        javax.swing.GroupLayout jPanelGradient1Layout = new javax.swing.GroupLayout(jPanelGradient1);
        jPanelGradient1.setLayout(jPanelGradient1Layout);
        jPanelGradient1Layout.setHorizontalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(lb_nama)
                .addGap(102, 102, 102))
        );
        jPanelGradient1Layout.setVerticalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_date))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pn_kanan.add(jPanelGradient1, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(250, 250, 250));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setPreferredSize(new java.awt.Dimension(1103, 508));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_utama.add(new Form_Dashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Aktifkan Look and Feel modern
                    UIManager.setLookAndFeel(new FlatLightLaf());

                    // (Opsional) Set font global agar tampak lebih tajam
                     Font uiFont = new Font("SansSerif", Font.PLAIN, 14);
            UIManager.put("defaultFont", uiFont);

            // (Opsional) Skala DPI jika pakai monitor besar (HiDPI)
//            UIScale.setUserScaleFactor(1.0f);
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                String userID = "ID_User";
                String levelUser = "Level";
                String namaUser = "Nama_User";

                new MenuUtama(userID, namaUser, levelUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sidemenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Palette.JPanelGradient jPanelGradient1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
   private void execute(String userID, String namaUser, String levelUser) {
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/Icons/Sorting.png"));
        ImageIcon iconDashboard = new ImageIcon(getClass().getResource("/Icons/Dashboard Layout.png"));
        ImageIcon iconMenu = new ImageIcon(getClass().getResource("/Icons/Food Bar1.png"));
        ImageIcon iconPelanggan = new ImageIcon(getClass().getResource("/Icons/Pelanggan.png"));
        ImageIcon iconKategori = new ImageIcon(getClass().getResource("/Icons/Restaurant.png"));
        ImageIcon iconMeja = new ImageIcon(getClass().getResource("/Icons/Table1.png"));
        ImageIcon iconUser = new ImageIcon(getClass().getResource("/Icons/Icon6.png"));
        ImageIcon iconPenjualan = new ImageIcon(getClass().getResource("/Icons/Transaksi.png"));
        ImageIcon iconLaporan = new ImageIcon(getClass().getResource("/Icons/Icon7.png"));
        ImageIcon iconLogout = new ImageIcon(getClass().getResource("/Icons/Open Pane.png"));

        Menu_Item masMenu1 = new Menu_Item(null, true, iconPelanggan, "Pelanggan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Pelanggan());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        Menu_Item masMenu2 = new Menu_Item(null, true, iconKategori, "Kategori", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Kategori());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        Menu_Item masMenu3 = new Menu_Item(null, true, iconMeja, "Meja", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Meja());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        Menu_Item masMenu4 = new Menu_Item(null, true, iconUser, "User", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_User());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        Menu_Item masMenu5 = new Menu_Item(null, true, iconMenu, "Menu", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Menu());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        Menu_Item transaksi1 = new Menu_Item(null, true, iconPenjualan, "Penjualan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Penjualann(userID));
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        Menu_Item laporan1 = new Menu_Item(null, true, iconLaporan, "Penjualan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Laporan_Penjualan(userID));
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        Menu_Item menuDashboard = new Menu_Item(iconDashboard, false, null, "Dashboard", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Dashboard());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        Menu_Item menuLogout = new Menu_Item(iconLogout, false, null, "Logout", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                FormLogin formLogin = new FormLogin();
                formLogin.setVisible(true);// Tutup MenuUtama
                dispose();
            }
        });

        Menu_Item menuMaster = new Menu_Item(iconMaster, false, null, "Master", null, masMenu1, masMenu2, masMenu3, masMenu4, masMenu5);
        Menu_Item menuTransaksi = new Menu_Item(iconMaster, false, null, "Transaksi", null, transaksi1);
        Menu_Item menuLaporan = new Menu_Item(iconMaster, false, null, "Laporan", null, laporan1);

        if (levelUser.equals("Admin")) {
            menuMaster = new Menu_Item(iconMaster, false, null, "Master", null, masMenu1, masMenu2, masMenu3, masMenu4, masMenu5);
            addMenu(menuDashboard, menuMaster, menuTransaksi, menuLaporan, menuLogout);
        } else {
            menuMaster = new Menu_Item(iconMaster, false, null, "Master", null, masMenu1); // Hanya masMenu1 untuk non-Admin
            addMenu(menuDashboard, menuMaster, menuTransaksi, menuLaporan, menuLogout);
        }
    }

    private void addMenu(Menu_Item... menu) {
        for (int i = 0; i < menu.length; i++) {
            Sidemenu.add(menu[i]);
            ArrayList<Menu_Item> subMenu = menu[i].getSubMenu();
            for (Menu_Item m : subMenu) {
                addMenu(m);
            }
        }
        Sidemenu.revalidate();
    }

}
